### ISSUE TITLE
Green pass revocati ma accettati

### ISSUE THREAD

**Issue by giga89** [ministero-salute/it-dgc-verificac19-sdk-android#100]
Buongiorno a tutti,
per far verificare se il green pass letto è tra i revocati è necessario cambiare qualcosa nell'uso dell'sdk?
Sto provando a leggere un certificato revocato e mi risulta valido con SDK 1.1.1 e non valido con VerificaC19.
Cosa sto sbagliando?
Grazie mille
Saluti

**Comment by rawmain** [comment]
Buongiorno @giga89 

> per far verificare se il green pass letto è tra i revocati è necessario cambiare qualcosa nell'uso dell'sdk? Sto provando a leggere un certificato revocato e mi risulta valido con SDK 1.1.1 e non valido con VerificaC19.

In caso di match-trigger `isRevoked` la funzione `getCertificateStatus` (in `VerificationViewModel`) restituisce l'esito intermedio `CertificateStatus.REVOKED` :

```
    fun getCertificateStatus(cert: CertificateModel): CertificateStatus {
        if (cert.isRevoked) return CertificateStatus.REVOKED
```

Devi quindi impostare il tuo codice app/UI in modo che lo riconosca & gestisca, onde restituire l'esito finale NOT_VALID in ambito produzione/release (_gli esiti intermedi possono essere mantenuti come esito finale solo per debug/test_). Vedasi come fa p.es. la whitelabel-app VerificaC19 (in `VerificationFragment`).

```
            CertificateStatus.REVOKED -> if (isDebug()) getString(R.string.certificateRevoked) else getString(
                R.string.certificateNonValid
```

In repo DGC-Documentazioni trovi anche il doc relativo a **[ScanMode - Tipologie di Verifica DGC](https://github.com/ministero-salute/it-dgc-documentation/blob/master/SCANMODE.md)** , qualora ti possa essere utile per verificare ulteriormente la gestione flussi esiti di validazione con tua app.

**Comment by giga89** [comment]
Grazie @rawmain , faccio qualche verifica riguardo a ciò che mi hai detto.
Grazie anche per il documento, non lo conoscevo ma è molto utile
Saluti

**Comment by giga89** [comment]
Ho fatto qualche verifica e in effetti la verifica lo fa.
Il problema è che non mi scarica il db dei revocati.. Sto facendo qualche altra prova per capire

Consultandomi con un collega ho verificato e il mio db sembra rimanere vuoto.

[VerificaC19.zip](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/files/7837705/VerificaC19.zip)
(togliete il .zip per aprire il file)

**Comment by giga89** [comment]
Aggiungo che mi entra nel metodo "getCRLStatus" e non esce più

![image](https://user-images.githubusercontent.com/1588412/148741502-d737f2b8-687a-4984-8ade-03dd4c39abc4.png)

**Comment by bobbysimon24** [comment]
Ciao @giga89,
Anche io ho avuto questo problema, lo ho appena risolto inserendo queste righe di codice:
![codice2](https://user-images.githubusercontent.com/26278924/148745813-cec300bf-b86c-4d24-9f49-660725a576f6.PNG)

![codice](https://user-images.githubusercontent.com/26278924/148745789-0cf210ed-ffa8-43bc-93cc-14bec4dc9dc2.PNG)

Lo ho preso da verificac19 quindi dovrebbe essere la procedura giusta.
Ovviamente è di test quindi va un attimo arrangiato, ma a me ha cominciato a scaricarli in questo modo, se guardi i log di info dovresti vedere il download in corso quando avvii questa funzione.
Fammi sapere se è di aiuto ;)

**Comment by giga89** [comment]
Grazie @bobbysimon24 !
La tua funzione ha molto senso in quanto dice che può iniziare il download.. Ti posso solo chiedere come istanziare il viewModel?
Grazie

Io al momento sto scrivendo in Java e il codice scritto fino ad ora è questo:
`    static FirstViewModel viewModel;

    static public void prepareForDownload()
    {
        viewModel.resetCurrentRetry();
        viewModel.setShouldInitDownload(true);
        viewModel.setDownloadAsAvailable();
    }
`

Naturalmente lo richiamerei prima del "setWorkManager" e ovviamente viewModel è null..
Lo creo come nuovo oggetto? Posso chiederti come hai fatto tu?

**Comment by bobbysimon24** [comment]
Io lo istanzio nella prima riga di codice che  vedi, dove lo dichiaro

> ![codice2](https://user-images.githubusercontent.com/26278924/148753498-a3bdf61d-0ef2-4b77-bc4d-f14817bb2bd6.PNG)


 solo che non credo che funzioni su java, prova a fare così:
`viewModel = new ViewModelProvider(this).get(FirstViewModel.class);`
Ti lascio il link della discussione di stackoverflow da cui lo ho preso nel caso ti servisse: https://stackoverflow.com/questions/57534730/as-viewmodelproviders-of-is-deprecated-how-should-i-create-object-of-viewmode

Purtroppo non posso testarlo al momento ma mi sembra che possa essere quello che ti serve

**Comment by giga89** [comment]
Grazie @bobbysimon24 , sei stato gentilissimo!
Cercherò di andare avanti dalle risorse che mi hai procurato

**Comment by giga89** [comment]
Ok ce l'ho fatta, @bobbysimon24 davvero grazie sei stato illuminante.

**Comment by bobbysimon24** [comment]
Figurati, felice di essere stato utile, buon proseguimento 👍
