### ISSUE TITLE
Preferences SDK

### ISSUE THREAD

**Issue by bobbysimon24** [ministero-salute/it-dgc-verificac19-sdk-android#113]
Ciao a tutti,
Aggiornando all'ultima versione delle SDK la mia app mi sono accorto che nelle preferenze non mi salva il valore "auth_to_resume", quindi non riesco a riprendere un download già iniziato e mi si blocca allo scarico dei dati, o almeno così mi sembra di capire. Qualcuno sa dirmi come mai non mi salva questo unico valore nelle preferenze? 
Ps: Ho provato a richiamare `firstViewModel.setResumeAsAvailable()` ma non cambia niente.

**Comment by rawmain** [comment]
Ciao @bobbysimon24 

> Aggiornando all'ultima versione delle SDK la mia app mi sono accorto che nelle preferenze non mi salva il valore "auth_to_resume"

Come puoi vedere dal [diff-compare DGC-SDK 1.1.1 vs 1.1.2](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/compare/release/1.1.1...release/1.1.2), non sono state apportate modifiche per la gestione della pref             `authToResume` .

Sono stati apportati invece i fix RealmConfiguration, onde evitare conflitti RealmModule, per cui devi verificare (_controllando le entry anteriori I/W/E in logcat_) se piuttosto il tuo codice app/UI non presenti issue p.es. durante `checkCurrentDownloadSize`, causa mancato allineamento a modifiche DGC-SDK. 

Con codice release 1.2.2 - build 638 whitelabel-app/UI VerificaC19 + release 1.1.2 DGC-SDK + ultimo update (3h fa) branch main EU DGCA Core non risultano infatti anomalie in merito (_ved. [apprelease sample](https://github.com/VC19rvk/it-dgc-verificaC19-android-RVK/releases/tag/1.2.2-RVK-20220124)_).

**Comment by bobbysimon24** [comment]
Ciao @rawmain grazie per la risposta,
Mi sono spiegato un po' male, grazie comunque per la risposta ma io intendevo che me ne sono accorto con l'ultimo aggiornamento ma credo che anche nelle vecchie versioni avessi questo problema e che non me ne fossi mai accorto, perchè ho provato ad aggiornare un'applicazione con queste sdk (Il primo avvio era avvenuto quindi con le sdk 1,1.1) e il file delle preferenze non ha proprio la voce  "auth_to_resume" al suo interno, la quale credo che sarebbe stata generata dalle precedenti sdk se tutto fosse andato bene (O no?).
Se provo a richiamare invece un'istanza delle preferenze e lo aggiorno da li invece mi compare, com'è possibile, non dovrebbe fare proprio questo il codice richiamato da `firstViewModel.setResumeAsAvailable()`?

**Comment by rawmain** [comment]
Ciao @bobbysimon24 

> grazie per la risposta,

Prego ;).

> non ha proprio la voce "auth_to_resume" al suo interno, la quale credo che sarebbe stata generata dalle precedenti sdk se tutto fosse andato bene (O no?). Se provo a richiamare invece un'istanza delle preferenze e lo aggiorno da li invece mi compare, com'è possibile, non dovrebbe fare proprio questo il codice richiamato da `firstViewModel.setResumeAsAvailable()`?

Deve essere comunque il tuo codice app/UI a richiamare la funzione definita in SDK per impostare in 1 (enabled) il valore pref `authtoResume`, come appunto fa il codice della whitelabel-app VerificaC19 in [FirstActivity](https://github.com/ministero-salute/it-dgc-verificaC19-android/blob/develop/app/src/main/java/it/ministerodellasalute/verificaC19/ui/FirstActivity.kt).

```
        binding.resumeDownload.setOnClickListener {
            if (Utility.isOnline(this)) {
                viewModel.setResumeAsAvailable()
                binding.resumeDownload.hide()
                binding.dateLastSyncText.text = getString(R.string.updatingRevokedPass)
                startSyncData()
            } else {
                createCheckConnectionAlertDialog()
            }
        }
```

Se il tuo codice app/UI implementa comunque correttamente il controllo/richiamo della funzione, allora devi controllare appunto tramite logcat cosa avvenga prima nell'esecuzione del tuo codice.

Qualora non riuscissi ancora a risolvere, sarebbe utile che fornissi un estratto del codice tua app/UI relativo alla gestione dei download e/o il relativo logcat di esecuzione.

**Comment by bobbysimon24** [comment]
Ciao @rawmain, grazie come sempre per l'aiuto,
A questo giro però è stata una mia svista, perchè richiamavo `firstViewModel.setResumeAsAvailable()` in una funzione suspend senza accorgermene (Maledetto copia incolla). Quindi non mi andava a scrivere il risultato nelle preferenze (Anche se devo ammettere che non mi è comunque chiaro fino in fondo il perchè).
Adesso tutto regolare 👍
