### ISSUE TITLE
IP da aprire su Firewall per il corretto funzionamento dell'sdk e della app VC19

### ISSUE THREAD

**Issue by ortorob73** [ministero-salute/it-dgc-verificac19-sdk-android#114]
Buongiorno

un ente statale ci chiede quali IP sono da aprire su firewall per il corretto funzionamento della APP relativa a tutti gli aspetti connessi (scaricamenti certificati, ecc).

E' possibile avere un elenco esaustivo?

Grazie

**Comment by rawmain** [comment]
Buongiorno @ortorob73 

> un ente statale ci chiede quali IP sono da aprire su firewall per il corretto funzionamento della APP relativa a tutti gli aspetti connessi (scaricamenti certificati, ecc).
> 
> E' possibile avere un elenco esaustivo?

Whitelabel-app e DGC-SDK VerificaC19 richiedono operativamente solo il permesso di connessione per verifica disponibilità & download degli aggiornamenti Rules (Validation Rules) / KIDs (Trustlist) / DRL . 

Pertanto, i parametri base di riferimento per la connessione remote host sono appunto quelli indicati in [sdk/build.gradle](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/blob/develop/sdk/build.gradle).

| SERVER_HOST | get.dgc.gov.it |
| :--------------: | :--------------: |
| Protocol / Port | HTTPS - TCP 443 |

Per quanto riguarda quindi il whitelist di indirizzi IP associati a tale hostname, dovete appunto tener conto dell'utilizzo della piattaforma Akamai Edge (`CNAME = get.dgc.gov.it.edgekey.net`), per cui non vi è risoluzione biunivoca & statica A per hostname<->IP.

Pertanto, avete 2 possibilità d'approccio per definire ACL di permesso per connessioni con CIDR block IPv4/IPv6 Akamai Edge : 

1. Usare la [Origin IP ACL Akamai](https://learn.akamai.com/en-us/webhelp/origin-ip-acl/origin-ip-acl-guide/GUID-E5AD1B2B-BDA1-4C3F-87DE-B0CDBDD1E1B0.html). 

2. Usare le [Firewall Rules Notification API Akamai](https://techdocs.akamai.com/firewall-rules/reference/api) con auth/token di account Akamai customer o [developer con abilitazione per OpenAPI](https://github.com/akamai/cli-firewall).

In caso di approccio 1 dovrete procedere autonomamente con monitoraggio di eventuali variazioni nei block utilizzati da Akamai, onde adeguare - se/quando necessario - ACL lato firewall. Inoltre, essendo una lista globale/statica, saranno autorizzate le connessioni anche verso IP Akamai distinti dagli Active IP associati al server Edge di appoggio.   

In caso invece di approccio 2 non è necessario un monitoraggio autonomo, dato che consente di gestire in modo programmatico le operazioni di controllo/applicazione degli aggiornamenti ACL. Inoltre consente una gestione più granulare, visto che consente di recuperare tramite API request solo l'elenco ristretto di interesse per le associazioni dinamiche edge-host/active-ip (_e.g. `get.dgc.gov.it.edgekey.net -> e88253.e3.akamaiedge.net -> Active IPs`_).
