### ISSUE TITLE
1000+ crash senza alcuna modifica all'utilizzo/import dell'SDK 

### ISSUE THREAD

**Issue by albertocappellina** [ministero-salute/it-dgc-verificac19-sdk-android#118]
Buongiorno,     dopo migliaia di attivazioni di greenpass in maniera impeccabile, oggi l'sdk ha portato/sta portando l'app a crashare con 1000+ crash su 1000+ utenti.

Gli errori sono sempre (piu' o meno) relativi al loop che avviene all'avvio dell'app, solo che prima non era mai avvenuto con il profilo di Release/sullo store

Es di crash:

Fatal Exception: kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[Dispatchers.IO, Continuation at it.ministerodellasalute.verificaC19sdk.data.VerifierRepositoryImpl$fetchCertificate$2.invokeSuspend(VerifierRepositoryImpl.kt:152)@701ad5c]){Completed}@fb10865. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
       at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)

Caused by java.lang.StackOverflowError: stack size 1041KB

--

Fatal Exception: kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[Dispatchers.IO, Continuation at it.ministerodellasalute.verificaC19sdk.data.VerifierRepositoryImpl$fetchCertificate$2.invokeSuspend(VerifierRepositoryImpl.kt:152)@701ad5c]){Completed}@fb10865. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
       at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)

Caused by java.lang.StackOverflowError: stack size 1041KB

Come possiamo rimediare ?

Grazie
Alberto

**Comment by bobbysimon24** [comment]
Ciao @albertocappellina ,
Mi accodo anche io, anche diverse delle mie applicazioni stamattina hanno dato problemi con gli aggiornamenti, devo ancora capire se è necessario un aggiornamento o si risolve riavviando l'app ma mi stanno arrivando sempre più segnalazioni.
