### ISSUE TITLE
Controllo sugli over 50

### ISSUE THREAD

**Issue by anpplnk** [ministero-salute/it-dgc-verificac19-sdk-android#122]
Che piani avete sulla implementazione del controllo che andrà in vigore dal 15 di Febbraio 2022, e che prevede il green pass rafforzato per gli over 50 sui luoghi di lavoro? Sarà implementato a livello di SDK? Se si, in che modo? 
Grazie anticipatamente

**Comment by bobbysimon24** [comment]
Ciao @anpplnk,
Tutto quello che so è che sarà implementata una nuova modalità chiamata "work", ma non si sa quando verrà rilasciata, o almeno io non ne sono al corrente.
Puoi trovare più informazioni in queste discussioni:
https://github.com/ministero-salute/it-dgc-documentation/issues/10
https://github.com/ministero-salute/it-dgc-verificaC19-android/issues/235
Spero che queste poche informazioni ti aiutino in qualche modo :)

**Comment by rawmain** [comment]
Buongiorno @anpplnk 

> Che piani avete sulla implementazione del controllo che andrà in vigore dal 15 di Febbraio 2022, e che prevede il green pass rafforzato per gli over 50 sui luoghi di lavoro? Sarà implementato a livello di SDK? Se si, in che modo?

Le condizioni per la gestione flussi del nuovo scanmode WORK (_Tipologia di Verifica : LAVORO_) sono presenti nella feature branch [`feature/work-scan-mode`](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/feature/work-scan-mode) .

Dato che riguarda appunto specifiche prescrizioni/disposizioni, che diventeranno effettive a partire dal 15 Febbraio, non è stata implementata nelle ultime prodrelease DGC-SDK 1.1.2 e 1.1.3. In ogni caso - _come sempre avvenuto finora_ - verrà integrata per tempo. 

Per il resto, la documentazione di dettaglio sui flussi scanmode è disponibile nella repo ufficiale [IT DGC-Documentation](https://github.com/ministero-salute/it-dgc-documentation). 

Gli aggiornamenti non ancora operativi di nuovi scanmode / condizioni di controllo non sono ancora state integrati, ma il relativo work-in-progress è comunque visionabile dal Pull-Request tracker di tale repo.

**Comment by AdelmoBianchini** [comment]
LA STORIA INSEGNA MA NON HA SCOLARI:
CHI CHIEDE IL GREENPASS È NAZISTA
E ANCHE CHI LO RENDE POSSIBILE TECNICAMENTE
#ViVi forza di lotta nonviolenta per libertà e diritti

**Comment by Roma77-alt** [comment]
Buongiorno, ci sono aggiornamenti rispetto al controllo gp over 50?

**Comment by Roma77-alt** [comment]
Abbiamo effettuato l'aggiornamento sul nostro lettore di green pass ed è comparsa la modalità di verifica qr code lavoratore rafforzata....è l'opzione corretta?

**Comment by rawmain** [comment]
Buongiorno @Roma77-alt 

> ci sono aggiornamenti rispetto al controllo gp over 50?

Nel release-tracker è stata pubblicata ieri la [`release/1.1.5`](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/release/1.1.5) del DGC-SDK Android/Kotlin, che integra tra i vari aggiornamenti (_ved. [changelog](https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding/blob/main/CHANGELOG.md)_) anche il supporto scanmode WORK (_tipologia di verifica LAVORO_).

Tale prodrelease DGC-SDK è la medesima in uso dalla release 1.2.5 di whitelabel-app Android VerificaC19, pubblicata anch'essa ieri - con contestuale rilascio delle storerelease su Google PlayStore & Huawei AppGallery.

**Comment by TorquatoLeopardi** [comment]
> Buongiorno @anpplnk
> 
> > Che piani avete sulla implementazione del controllo che andrà in vigore dal 15 di Febbraio 2022, e che prevede il green pass rafforzato per gli over 50 sui luoghi di lavoro? Sarà implementato a livello di SDK? Se si, in che modo?
> 
> Le condizioni per la gestione flussi del nuovo scanmode WORK (_Tipologia di Verifica : LAVORO_) sono presenti nella feature branch [`feature/work-scan-mode`](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/feature/work-scan-mode) .
> 
> Dato che riguarda appunto specifiche prescrizioni/disposizioni, che diventeranno effettive a partire dal 15 Febbraio, non è stata implementata nelle ultime prodrelease DGC-SDK 1.1.2 e 1.1.3. In ogni caso - _come sempre avvenuto finora_ - verrà integrata per tempo.
> 
> Per il resto, la documentazione di dettaglio sui flussi scanmode è disponibile nella repo ufficiale [IT DGC-Documentation](https://github.com/ministero-salute/it-dgc-documentation).
> 
> Gli aggiornamenti non ancora operativi di nuovi scanmode / condizioni di controllo non sono ancora state integrati, ma il relativo work-in-progress è comunque visionabile dal Pull-Request tracker di tale repo.

La storia insegna ma non ha scolari: chi chiede il green pass è nazista, e anche chi lo rende tecnicamente possibile. 

Draghi e Speranza = boia nazisti

ViVi forza di lotta nonviolenta per libertà e diritti 
Cerca su tleregam Entra_in_v_v 


**Describe the bug**


**To Reproduce**


**Expected behavior**


**Screenshots**


**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.-->
