### ISSUE TITLE
Potential regression in vaccineStandardStrategy

### ISSUE THREAD

**Issue by DevTrevi** [ministero-salute/it-dgc-verificac19-sdk-android#130]
Hi everyone,

in the new `vaccineStandardStrategy` in the upcoming version 1.1.5, the rules read from service are always referred to "IT" (Italy), but they was implemented in this way just a few commits before:

``
val countryCode = if (scanMode == ScanMode.STANDARD) vaccination.countryOfVaccination else Country.IT.value
``

Is this a regression or it is an intended change?

**Comment by rawmain** [comment]
Hello @DevTrevi 

> in the new `vaccineStandardStrategy` in the upcoming version 1.1.5, the rules read from service are always referred to "IT" (Italy), but they was implemented in this way just a few commits before
[...]
> Is this a regression or it is an intended change?

It's an intended change. Current arrangement for some Vaccine Validation Strategy ruleset values' choice relies indeed on : 

- `Country.IT.value` for INTERNAL scenario scanmodes = Standard (3G) - Strengthened (2G) - Booster - School - Work

- `Country.NOT_IT.value` only for TRAVEL IntraEU scenario scanmodes = Entry

EMA checks (mp / extendedDays) for status override rely instead always on (vaccination.medicinalProduct, vaccination.countryOfVaccination).

**Comment by DevTrevi** [comment]
Thank you @rawmain
