### ISSUE TITLE
Realm crash con nuova versione

### ISSUE THREAD

**Issue by bobbysimon24** [ministero-salute/it-dgc-verificac19-sdk-android#131]
Buonasera,

Scrivo perchè sto testando le nuove modifiche presenti in develop che dovranno essere promosse a release entro poco.
Quando provo a validare un green pass in qualsiasi modalità mi va in crash realm, con questo messaggio: `RevokedPass is not part of the schema for this Realm`
Sapete dirmi la causa? Documentandomi molto velocemente sembra che si risolva scambiando le dichiarazioni dei plug in nel build.gradle, ma mi sembra che sia già l'ordine giusto.
Qualcuno ha avuto il problema?

**Comment by rawmain** [comment]
Buonasera @bobbysimon24 

> Quando provo a validare un green pass in qualsiasi modalità mi va in crash realm, con questo messaggio: `RevokedPass is not part of the schema for this Realm` Sapete dirmi la causa? Documentandomi molto velocemente sembra che si risolva scambiando le dichiarazioni dei plug in nel build.gradle, ma mi sembra che sia già l'ordine giusto.

Controlla la dichiarazione dei plugin nel build.gradle della tua app (non del DGC-SDK), confrontandola con quella nel [build.gradle della whitelabel-app VerificaC19](https://github.com/ministero-salute/it-dgc-verificaC19-android/blob/develop/app/build.gradle).

Se non stai effettuando i test con tuo codice app, bensì con il codice whitelabel-app, verifica con diff/compare se non ci sia stato un disallineamento durante tuo merge/update.

**Comment by Kaizen-7** [comment]
Condivido quanto suggerito da @rawmain, inoltre ho provato a fare un test da versione 1.2.4 a 1.2.5, per scovare potenziali issue di migrazione, ma non sembrano esserci problemi in questo senso.

**Comment by bobbysimon24** [comment]
Buongiorno, grazie per le risposte.
Sto provando ora a fare come avete detto, i miei plug-in ora sono identici a quelli di verificaC19, ma continuo ad avere sempre quel problema.

**Comment by bobbysimon24** [comment]
Ok, ho appena risolto. A quanto pare inizializzavo nel modo sbagliato Realm, adesso funziona, grazie come sempre per le risposte
👍
