### ISSUE TITLE
Errore in compilazione aggiornando alla versione 1.1.5

### ISSUE THREAD

**Issue by giga89** [ministero-salute/it-dgc-verificac19-sdk-android#132]
Semplicemente aggiornando l'sdk ho questo errore di compilazione

Caused by: groovy.lang.MissingPropertyException: No such property: gson for class: Deps

Come risolvere?

**Comment by rawmain** [comment]
Buonasera @giga89 

> aggiornando l'sdk ho questo errore di compilazione
> 
> Caused by: groovy.lang.MissingPropertyException: No such property: gson for class: Deps

Verifica tramite diff/compare e/o confronto storico commit con la branch [`release/1.1.5`](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/release/1.1.5) se non ci sia stato un disallineamento durante merge/update della tua repo. Le ultime modifiche in DGC-SDK relative a gson deps sono quelle del commit di refactoring [`505f296`](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/commit/505f296795dfe6bb1b088c4344a7dbce7da4db9d) .

Se non risultano disallineamenti & non stai usando per app/UI il codice whitelabel-app VerificaC19, bensì tuo codice, verifica che non ci siano a livello di progetto/app conflitti/override delle dipendenze, usando come riferimento le impostazioni deps/versions della whitelabel-app.

**Comment by giga89** [comment]
Ho risolto aggiornando i file Version.kt e Dependencies.kt della mia app.
Grazie mille
