### ISSUE TITLE
Dubbio nuovo parametro per scansione

### ISSUE THREAD

**Issue by loreberti89** [ministero-salute/it-dgc-verificac19-sdk-android#134]
# Issue content
Ciao, con la nuova versione, non dobbiamo più inviare una stringa al verificationViewModel ma un enum della sdk.
Ora io sto mandando la stessa stringa ma poi faccio il 
`ScanMode.Companion.from(scanModeParams)`
Per avere lo scanmode object da poter inviare alla funzione decode.
Ma non capisco, io sto inviando la stringa BOOSTED , come nella vecchia versione, con un certificato di guarigione (a seguito di ciclo completo di vaccinazione 2 dosi), ma il risultato del certificato  mi viene restituito VALID, mentre mi sarei aspettato un TEST_NEEDED come nella vecchia versione.
Mi sto perdendo qualcosa o è giusto cosi?

**Comment by giga89** [comment]
Ciao @loreberti89 ,
anche io mi sono accorto della differenza.
Credo comunque sia più giusto come è ora in quanto, mi pare di aver capito, che 2 dosi + guarigione equivalgono a 3 dosi.
Sbaglio?
Ciao

**Comment by DevPGS** [comment]
esatto,
alcuni greenpass hanno un tag speciale nel certificato di firma che indica la guarigione post-vaccinazione, il controllo in scanmode BOOSTED verifica questo tag e restituisce l'esito indicato ([vedi qui](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/blob/70909c86c9de0d609a2a3d932171c332819f1117/sdk/src/main/java/it/ministerodellasalute/verificaC19sdk/model/validation/RecoveryValidationStrategy.kt#L60))

**Comment by loreberti89** [comment]
> esatto, alcuni greenpass hanno un tag speciale nel certificato di firma che indica la guarigione post-vaccinazione, il controllo in scanmode BOOSTED verifica questo tag e restituisce l'esito indicato ([vedi qui](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/blob/70909c86c9de0d609a2a3d932171c332819f1117/sdk/src/main/java/it/ministerodellasalute/verificaC19sdk/model/validation/RecoveryValidationStrategy.kt#L60))

Grazie, stavo guardando proprio ora qua:
https://github.com/rawmain/it-dgc-documentation/blob/feat/scanmode-work-school-exemption/SCANMODE.md
E in effetti i gp r-pv quindi suppongo recovery post vaccine sono considerati alla stregua dei booster.
Ok
Ottimo.

Chiudo issue.
