### ISSUE TITLE
Modalità BOOSTER

### ISSUE THREAD

**Issue by bobbysimon24** [ministero-salute/it-dgc-verificac19-sdk-android#135]
Buonasera, nuovo giorno nuovo Issue ormai mi viene da dire...
Oggi aggiornando le SDK alla versione di release mi sono accorto che in modalità booster mi da come valido il mio certificato di guarigione, con solo 2 dosi, su verifica C19 invece chiede il tampone.
Dopo averci guardato un po' ho visto che la variabile "rcoveryBis" è a true, quando dovrebbe essere a false perchè mi dia il risultato giusto. Non capisco però a cosa serva questa variabile e da cosa venga ricavata.
Qualcuno sa darmi un aiuto?

**Comment by loreberti89** [comment]
> Buonasera, nuovo giorno nuovo Issue ormai mi viene da dire... Oggi aggiornando le SDK alla versione di release mi sono accorto che in modalità booster mi da come valido il mio certificato di guarigione, con solo 2 dosi, su verifica C19 invece chiede il tampone. Dopo averci guardato un po' ho visto che la variabile "rcoveryBis" è a true, quando dovrebbe essere a false perchè mi dia il risultato giusto. Non capisco però a cosa serva questa variabile e da cosa venga ricavata. Qualcuno sa darmi un aiuto?

Ciao, hai provato ad aggiornare anche verifica c-19?
Nelle nuove regole il GP con guardigione + 2 dosi è comparabile al BOOSTED

guarda anche il Issue che ho aperto io stamani #134 

Ciao!

**Comment by DevPGS** [comment]
in ogni caso recoveryBis è ricavata dai dati presenti nel certificato di firma del greenpass, se è presente in 'extensions' un valore 
 'extendedKeyUsage' pari a:
```
 OID_RECOVERY = "1.3.6.1.4.1.1847.2021.1.3";
 OID_ALT_RECOVERY = "1.3.6.1.4.1.0.1847.2021.1.3";
```
e lo stato emettitore è IT, allora recoveryBis è `true`

**Comment by bobbysimon24** [comment]
Grazie per le risposte, 
In effetti non avevo previsto questa possibilità :)
Grazie per i chiarimenti
