### ISSUE TITLE
Parametro SDK_MIN_VERSION("sdk") assente sulle validation sule

### ISSUE THREAD

**Issue by a-bellezza** [ministero-salute/it-dgc-verificac19-sdk-android#142]
Salve.

Stavo notando che sulle validation rule al momento è assente il parametro "sdk" per il check della versione della libreria.

E' voluta come cosa ? Oppure è un'anomalia ?

Grazie in anticipo.

**Comment by rawmain** [comment]
Buongiorno @a-bellezza 
 
> Stavo notando che sulle validation rule al momento è assente il parametro "sdk" per il check della versione della libreria.

Il value della versione DGC-SDK è stato rimosso dal [JSON delle Validation Rules](https://get.dgc.gov.it/v1/dgc/settings) mesi fa (Novembre) quando sono iniziate le approvazioni di [SDK/Librerie terze autorizzate dal Ministero della Salute](https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding).

Le soluzioni, che integrano SDK/Lib autorizzate, possono infatti fare un controllo più puntuale / non in ritardo di allineamento con rilasci versioni DGC-SDK, effettuando la verifica del value per `tag_name` dal [latest-release tracker](https://api.github.com/repos/ministero-salute/it-dgc-verificac19-sdk-android/releases/latest).

**Comment by a-bellezza** [comment]
Ma quindi qualunque app che non usa l'ultima versione dell'sdk sta usando un sdk obsoleto ?
Solo l'ultima versione dell'sdk è quella valida ?

**Comment by rawmain** [comment]
Buonasera @a-bellezza 

> Ma quindi qualunque app che non usa l'ultima versione dell'sdk sta usando un sdk obsoleto ? Solo l'ultima versione dell'sdk è quella valida ?

Si, come puoi vedere anche dal [changelog sintetico DGC-SDK](https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding/blob/main/CHANGELOG.md). 

Le versioni precedenti alla release DGC-SDK 1.1.5 NON implementano le ulteriori condizioni di validazione / medical-rules - previste da [DL n°5/2022](https://www.trovanorme.salute.gov.it/norme/dettaglioAtto?id=85657).

Pertanto, anche le app, che integrino/usino DGC-SDK solo per supporto scanmode Base e/o Rafforzata, devono comunque utilizzare ora la versione 1.1.5 .

Idem, per quanto concerne app/soluzioni con utilizzo SDK/Lib terze autorizzate dal Ministero della Salute ex DPCM 12/10/2021 = conformità delle validazioni solo con integrazione versioni lib terze allineate a feature DGC-SDK 1.1.5 (ved. [tabella in lista librerie](https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding#lista-librerie)).
