### ISSUE TITLE
[Feature Request] Cambiare il popup di scelta tipo verifica con un'activity a sé

### ISSUE THREAD

**Issue by vixrt** [ministero-salute/it-dgc-verificac19-sdk-android#143]
![img_vc19 - Copia](https://user-images.githubusercontent.com/65950712/155529813-940d296c-5441-4595-afc3-e6a3d2df5250.jpg)

Attualmente si può scegliere fra 6 tipi di verifica, presentando all'utente un popup decisamente brutto. 

Arrivati a questo punto, visto anche che alcune risoluzioni schermo di alcuni dispositivi sono veramente basse, direi che è oppurtuno valutare, anche in vista di eventuali ingressi nelle tipologie di verifica, di spostare la selezione della verifica in una activity separata.
https://developer.android.com/reference/android/app/Activity

Nell'activity separata sarà più facile, graficamente, illustrare le varie modalità, descrivere cosa comprende ciascuna, ecc...

https://github.com/ministero-salute/it-dgc-verificaC19-android/issues/265

**Comment by giga89** [comment]
Considerando che questo è il progetto dell'SDK e non dell'applicazione direi che non ha molto senso questo issue..

**Comment by vixrt** [comment]
chiusa in favore di https://github.com/ministero-salute/it-dgc-verificaC19-android/issues/265
