### ISSUE TITLE
Mancato rilascio per nuove direttive 1 Aprile 2022

### ISSUE THREAD

**Issue by loreberti89** [ministero-salute/it-dgc-verificac19-sdk-android#163]
Ciao,
ma c'è una ragione per cui non è ancora stata rilasciata la nuova sdk in seguito alla fine dello stato di emergenza e ai nuovi regolamenti?

Ho visto che ci sono dei commit relativi alla rimozione dei metodi di scan WORK e SCHOOL e nella mia app ho provveduto a impostare 3G nel caso fosse stata impostata quella modalità di scansione, ma vorrei sapere se ci sarà un nuovo rilascio oppure se dobbiamo gestircela noi lato nostro applicativo.

Grazie.

**Comment by rawmain** [comment]
Ciao @loreberti89 

> c'è una ragione per cui non è ancora stata rilasciata la nuova sdk in seguito alla fine dello stato di emergenza e ai nuovi regolamenti?
>
> Ho visto che ci sono dei commit relativi alla rimozione dei metodi di scan WORK e SCHOOL e nella mia app ho provveduto a impostare 3G nel caso fosse stata impostata quella modalità di scansione

L'impostazione corretta di conformità alle disposizioni vigenti per le app terze integranti DGC-SDK Android/Kotlin prevede in realtà la disabilitazione / rimozione - _non l'override_ - delle scelte/opzioni di tipologie di verifica, che non siano più utilizzabili dalle app terze.

Pertanto : 

1. **Va rimossa lato codice terzo app/UI la scelta/opzione per tipologia di verifica Lavoro / selezione scanmode WORK**, onde essere conforme alle disposizioni del [DL n°24/2022](https://www.gazzettaufficiale.it/eli/id/2022/03/24/22G00034/sg)

2. **Va rimossa lato codice terzo app/UI anche la scelta/opzione per tipologia di verifica Studenti / selezione scanmode SCHOOL**, qualora questa non sia già stata effettuata correttamente a Febbraio - in conformità alle disposizioni del [DL n°5/2022](https://www.gazzettaufficiale.it/eli/id/2022/02/04/22G00014/sg) (_che già allora aveva ristretto l'autorizzazione all'uso di tale tipologia solo con le verifier-app VerificaC19 per iOS e Android, vietandolo a tutte le app/soluzioni terze_)


La release DGC-SDK 1.1.6 permane quindi valida/utilizzabile in conformità alle disposizioni vigenti. Ecco perché non vi è stato ancora bump/update di prodrelease nel tracker pubblico.

**Comment by loreberti89** [comment]
> Ciao @loreberti89
> 
> > c'è una ragione per cui non è ancora stata rilasciata la nuova sdk in seguito alla fine dello stato di emergenza e ai nuovi regolamenti?
> > Ho visto che ci sono dei commit relativi alla rimozione dei metodi di scan WORK e SCHOOL e nella mia app ho provveduto a impostare 3G nel caso fosse stata impostata quella modalità di scansione
> 
> L'impostazione corretta di conformità alle disposizioni vigenti per le app terze integranti DGC-SDK Android/Kotlin prevede in realtà la disabilitazione / rimozione - _non l'override_ - delle scelte/opzioni di tipologie di verifica, che non siano più utilizzabili dalle app terze.
> 
> Pertanto :
> 
> 1. **Va rimossa lato codice terzo app/UI la scelta/opzione per tipologia di verifica Lavoro / selezione scanmode WORK**, onde essere conforme alle disposizioni del [DL n°24/2022](https://www.gazzettaufficiale.it/eli/id/2022/03/24/22G00034/sg)
> 2. **Va rimossa lato codice terzo app/UI anche la scelta/opzione per tipologia di verifica Studenti / selezione scanmode SCHOOL**, qualora questa non sia già stata effettuata correttamente a Febbraio - in conformità alle disposizioni del [DL n°5/2022](https://www.gazzettaufficiale.it/eli/id/2022/02/04/22G00014/sg) (_che già allora aveva ristretto l'autorizzazione all'uso di tale tipologia solo con le verifier-app VerificaC19 per iOS e Android, vietandolo a tutte le app/soluzioni terze_)
> 
> La release DGC-SDK 1.1.6 permane quindi valida/utilizzabile in conformità alle disposizioni vigenti. Ecco perché non vi è stato ancora bump/update di prodrelease nel tracker pubblico.

Ok, chiaro.
Grazie.
