### ISSUE TITLE
Libreria software in python

### ISSUE THREAD

**Issue by federicocaroli** [ministero-salute/it-dgc-verificac19-sdk-android#21]
# Issue content
Buongiorno, dopo l'uscita del DPCM del 12 ottobre che specifica la possibilità di creare librerie software custom che seguano le specifiche usate in questo SDK per l'implementazione di un software di verifica dei green pass volevo chiedere dove fosse necessario pubblicare la libreria da noi realizzata in Python per la verifica di green pass.

**Comment by herald-si** [comment]
Buongiorno, mi accodo alla richiesta di conoscere quali siano le modalità per pubblicare la libreria da noi realizzata (PHP).

**Comment by irrisolto** [comment]
prova su [pypi.org](pypi.org)
