### ISSUE TITLE
Compatibilità SDK

### ISSUE THREAD

**Issue by pieropetralla90** [ministero-salute/it-dgc-verificac19-sdk-android#27]
# Issue content
E' possibile utilizzare l'sdk in un progetto ionic o flutter?
Come posso avere accesso ai metodi indicati dopo aver aggiunto i riferimenti nel settings.gradle?

**Comment by rox85** [comment]
> # Issue content
> E' possibile utilizzare l'sdk in un progetto ionic o flutter? Come posso avere accesso ai metodi indicati dopo aver aggiunto i riferimenti nel settings.gradle?

Stiamo provando anche noi ad integrare la funzionalità all'interno di un plugin di flutter, al momento senza successo. Non riusciamo a chiamare i metodi dell'SDK.

**Comment by loreberti89** [comment]
Buongiorno, 
Anche io ieri ho provato, ma non mi è chiaro.
Ho creato un plugin di flutter, importato le repo al pari, messe nel settings gradle, il plugin compila, ma come voi non riesco a capire come richiamare il metodo e le classi del sdk.

**Comment by FrancescoPenasa** [comment]
Buongiorno,
anche io con lo stesso problema se qualcuno riuscisse a farlo funzionare e magari anche a farne una guida sarebbe super utile per altri progetti di questo tipo, come ad esempio la `INPS-it/SPIDlibraryAndroid` e `italia/cieid-android-sdk`
