### ISSUE TITLE
Creare una libreria che si possa importare tramite Gradle

### ISSUE THREAD

**Issue by acaliaro** [ministero-salute/it-dgc-verificac19-sdk-android#28]
Sembra che ad oggi l'unico modo per utilizzare l'sdk sia quello di scaricare vari sorgenti. Perchè non si può fornire un sdk come una libreria gestibile tramite gradle, così che lo sviluppatore possa importare la libreria e utilizzare i suoi metodi senza dover avere altri sorgenti da gestire

**Comment by andrearavalli** [comment]
Forse si potrebbe rinominare "Creare una libreria" dato che, al momento, non è una libreria ma una accozzaglia di file

**Comment by bobvann** [comment]
quantomeno, si potrebbero usare i submodules di GIT se non si riesce a creare un pacchetto
