### ISSUE TITLE
Web API

### ISSUE THREAD

**Issue by FrancescoBonizzi** [ministero-salute/it-dgc-verificac19-sdk-android#36]
**Is your feature request related to a problem? Please describe.**
Sarebbe molto utile poter esporre una Web API per la validazione Green Pass, anche auto hostato. Il punto è che si possono avere client scritti in linguaggi diversi e per i quali la libreria Android non é referenziabile.

**Describe the solution you'd like**
Pubblicare un progetto il cui compilato si possa hostare e deployare come Web API ed interrogare tramite metodi REST.

**Comment by rox85** [comment]
> **Is your feature request related to a problem? Please describe.** Sarebbe molto utile poter esporre una Web API per la validazione Green Pass, anche auto hostato. Il punto è che si possono avere client scritti in linguaggi diversi e per i quali la libreria Android non é referenziabile.
> 
> **Describe the solution you'd like** Pubblicare un progetto il cui compilato si possa hostare e deployare come Web API ed interrogare tramite metodi REST.

Concordo ed in teoria con la versione node.js è praticamente istantanea la creazione di un webservice.  La questione è che non so se sia valido ai fine dell'ultimo DCPM.  ### Vedi riferimento: https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/issues/24

**Comment by enrico-mc** [comment]
Concordo, avete novità a riguardo?

**Comment by DevPGS** [comment]
https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding
qui c'è l'elenco delle librerie utilizzabili
