### ISSUE TITLE
LoadKeysWorker - come funziona?

### ISSUE THREAD

**Issue by fpalladino** [ministero-salute/it-dgc-verificac19-sdk-android#37]
# Issue content
Dalla documentazione leggo:
_"A questo punto è possibile inizializzare il workmanager (LoadKeysWorker) posizionato in it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker che consente di sincronizzare le regole di validazione e i certificati di firma prima di iniziare ad utilizzare l'applicazione."_

E' possibile avere un esempio di come inizializzarlo?

Grazie

**Comment by sirol81** [comment]
forse ancor meglio come fatto qui in VerificaC19 al _private fun setWorkManager()_
https://github.com/ministero-salute/it-dgc-verificaC19-android/blob/develop/app/src/main/java/it/ministerodellasalute/verificaC19/VerificaApplication.kt

**Comment by fpalladino** [comment]
> forse ancor meglio come fatto qui in VerificaC19 al _private fun setWorkManager()_ https://github.com/ministero-salute/it-dgc-verificaC19-android/blob/develop/app/src/main/java/it/ministerodellasalute/verificaC19/VerificaApplication.kt

Grazie

**Comment by danyalberton** [comment]
Ciao, scopiazzando dall'app VerificaC19, io sono riuscito ad inizializzare il WorkManager, ma ottengo un errore durante l'esecuzione. Di seguito riporto comunque gli step utili all'inizializzazione.

--- Per  progetti Java ---
1. Estendere la classe "Application" per personalizzare la configurazione dell'app (vedi come fare su https://guides.codepath.com/android/Understanding-the-Android-Application-Class)
2. Nella classe creata al punto 1 aggiungere la variabile `@Inject private HiltWorkerFactory workerFactory;`
3. Nella stessa classe implementare `androidx.work.Configuration.Provider`
4. Aggiungere le seguenti funzioni:
```
    @NonNull
    @Override
    public androidx.work.Configuration getWorkManagerConfiguration() {
        return new androidx.work.Configuration.Builder()
                .setWorkerFactory(workerFactory)
                .build();
    }

    private void setWorkManager() {
        // Java
        WorkRequest uploadWorkRequest = new PeriodicWorkRequest.Builder(LoadKeysWorker.class, 1, TimeUnit.DAYS)
                .setConstraints(new Constraints.Builder().setRequiredNetworkType(NetworkType.CONNECTED).build())
                .build();
        WorkManager.getInstance(this)
                .enqueueUniquePeriodicWork("LoadKeysWorker", ExistingPeriodicWorkPolicy.REPLACE, (PeriodicWorkRequest)uploadWorkRequest);
    }
```
5. Nella funzione `onCreate` aggiungere la chiamata a `setWorkManager();`
6. Ovviamente importare le librerie richieste, e quindi:
```
import androidx.hilt.work.HiltWorkerFactory;
import androidx.work.Constraints;
import androidx.work.ExistingPeriodicWorkPolicy;
import androidx.work.NetworkType;
import androidx.work.PeriodicWorkRequest;
import androidx.work.WorkManager;
import androidx.work.WorkRequest;

import java.util.concurrent.TimeUnit;
import javax.inject.Inject;
import it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker;
```
7. Nel Manifest aggiungere il seguente codice al tag `application`:
```
<provider
    android:name="androidx.work.impl.WorkManagerInitializer"
    android:authorities="${applicationId}.workmanager-init"
    android:exported="false"
    tools:node="remove" />
```
----
Così facendo riesco a compilare ed eseguire il progetto, ottengo però il seguente errore durante l'esecuzione:
```
E/WM-WorkerFactory: Could not instantiate it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker
    java.lang.NoSuchMethodException: it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker.<init> [class android.content.Context, class androidx.work.WorkerParameters]
```
Qualcun altro ha riscontrato il mio stesso problema?

**Comment by ivanoalonzi** [comment]
Ciao @danyalberton, hai capito come risolvere il problema? Sono nella tua stessa situazione.

Saluti

**Comment by PaoloG1980** [comment]
> 3\. Nella stessa classe implementare `androidx.work.Configuration.Provider`

Scusa l'ignoranza, ma cosa intendi per implementare `androidx.work.Configuration.Provider`?
Grazie

**Comment by danyalberton** [comment]
> Scusa l'ignoranza, ma cosa intendi per implementare `androidx.work.Configuration.Provider`? Grazie

@PaoloG1980  Ti riporto il link ad un post di @ivanoalonzi in cui riporta il codice di esempio della classe App (che estende `Application` e implementa `Configuration.Provider`).
Unico appunto: manca la chiamata alla funzione `setWorkManager()` da inserire nell'`onCreate()`.

https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/issues/42#issuecomment-947505882
