### ISSUE TITLE
istanziare VerificationViewModel

### ISSUE THREAD

**Issue by sirol81** [ministero-salute/it-dgc-verificac19-sdk-android#39]
le istruzioni recitano:
"A questo punto è possibile utilizzare una libreria di scansione di QR Code a scelta che, dopo aver letto un QR Code di un EU DCC, passi la stringa estratta a
_it.ministerodellasalute.verificaC19sdk.model.VerificationViewModel#init_.
Esempio:
`try {`  
`    viewModel.init(args.qrCodeText)`
`}`"

l'esempio non mostra come istanziare correttamente il viewModel di tipo VerificationViewModel

guardando quanto fatto in VerificaC19, mi perdo tra Provider, Factory, HiltModules, Fragments e non riesco a sfruttare correttamente lo snippet seguente
`viewModel.certificate.observe(viewLifecycleOwner) { certificate ->
            certificate?.let {
                certificateModel = it
                setPersonData(it.person, it.dateOfBirth)
                setupCertStatusView(it)
                setupTimeStamp(it)
                if (viewModel.getTotemMode() && (certificate.certificateStatus == CertificateStatus.VALID
                    || certificate.certificateStatus == CertificateStatus.PARTIALLY_VALID)) {
                    Handler().postDelayed({
                        activity?.onBackPressed()
                    }, 5000)
                }
            }
        }
        viewModel.inProgress.observe(viewLifecycleOwner) {
            binding.progressBar.isVisible = it
        }`
che teoricamente precede il viewModel.init

si potrebbe avere un working example semplice ma funzionante? grazie

**Comment by ivanoalonzi** [comment]
Mi accodo alla richiesta.

Grazie

**Comment by ivanoalonzi** [comment]
Io ho risolto marcando l'activity che si occupa del controllo con l'oggetto VerificationViewModel con l'annotation '@AndroidEntrypoint'
A questo punto ho preso l'oggetto di tipo VerificationViewModel nel modo seguente:
verificationViewModel = new ViewModelProvider(this).get(VerificationViewModel.class);

E poi ho invocato la funzione init. Non devi istanziare alcun oggetto.

Ora sono fermo alla definizione dell'observer con il quale determinare se il Green Pass è valido o meno. Io ho fatto così ma al termine della validazione, l'obesrver non riceve alcuna notifica.
final Observer certObserver = new Observer(){
'@Override'
public void onChanged(CertificateSimple certificateSimple) {
Log.d(TAG + "Observer) ", certificateSimple.getCertificateStatus().toString());
}
};

        verificationViewModel.getCertificate().observe(this, certObserver);
