### ISSUE TITLE
Istanziare un oggetto di tipo VerifierRepository

### ISSUE THREAD

**Issue by viseldev** [ministero-salute/it-dgc-verificac19-sdk-android#42]
Ciao a tutti,
premetto che sto programmando in Java.

Sono arrivato al punto di avere la necessità di istanziare un oggetto di tipo VerifierRepository (che credo si occupi della validazione online del certificato) tramite la creazione di un oggetto di tipo VerifierRepositoryImpl. Questo oggetto chiede diversi parametri nel costruttore, tra cui uno di tipo ApiService che non ha una implementazione di default.

Qualche suggerimento?

**Comment by ivanoalonzi** [comment]
ciao @viseldev, non so se sei fermo in questo punto ma ti dico come sono andato avanti.
Io ho risolto marcando l'activity che si occupa del controllo con l'oggetto VerificationViewModel con l'annotation @AndroidEntryPoint.
A questo punto ho preso l'oggetto di tipo VerificationViewModel nel modo seguente:
verificationViewModel = new ViewModelProvider(this).get(VerificationViewModel.class);

E poi ho invocato la funzione init. Non devi istanziare alcun oggetto.

Ora sono fermo alla definizione dell'observer con il quale determinare se il Green Pass è valido o meno. Io ho fatto così ma al termine della validazione, l'obesrver non riceve alcuna notifica.
           final Observer<CertificateSimple> certObserver = new Observer<CertificateSimple>(){
                @Override
                public void onChanged(CertificateSimple certificateSimple) {
                    Log.d(TAG + "Observer) ", certificateSimple.getCertificateStatus().toString());
                }
            };

            verificationViewModel.getCertificate().observe(this, certObserver);

Saluti

**Comment by viseldev** [comment]
Ciao @ivanoalonzi , ho provato a fare come suggerisci ma ottengo un ClassCastException sul "this" di new ViewModelProvider(this) che inizialmente era un errore di parametro non compatibile. Sto sbagliando qualcosa?

**Comment by ivanoalonzi** [comment]
In allegato ti lascio la mia MainActivity ed il file App nei quali sto facendo le prove di invocazione a questo sdk 
[MainActivity.txt](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/files/7380094/MainActivity.txt)
[App.txt](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/files/7380103/App.txt)

)

**Comment by ivanoalonzi** [comment]
@viseldev tienei presente che io sono partito da un progetto nuovo seguendo l'ultima guida fatta a Step pubblicata dal Ministero.

**Comment by viseldev** [comment]
@ivanoalonzi estendendo l'activity con AppCompatActivity l'errore sparisce ma ottengo questa exception durante la creazione del VerificationViewModel: java.lang.RuntimeException: Cannot create an instance of class it.ministerodellasalute.verificaC19sdk.model.VerificationViewModel

**Comment by ivanoalonzi** [comment]
Secondo me ti mancano delle dipendenze. Io proverei a rifare il progetto da capo seguendo l'ultima guida. Anche io quando la nuova guida non esisteva non riuscivo ad istanziare il LoadKeysWorker

**Comment by viseldev** [comment]
@ivanoalonzi probabile che l'errore sia dato dal fatto che non ho creato la classe App che estende Application che implementa Configuration.Provider ma ho delegato la main activity tutto il lavoro della creazione del Worker?

**Comment by danyalberton** [comment]
> In allegato ti lascio la mia MainActivity ed il file App nei quali sto facendo le prove di invocazione a questo sdk [MainActivity.txt](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/files/7380094/MainActivity.txt) [App.txt](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/files/7380103/App.txt)
> 
> )

Vedo che nella classe `App`, nel metodo `onCreate()`, manca la chiamata alla funzione `setWorkManager()`.
Introducendo la chiamata riesci a inizializzare correttamente il `LoadKeysWorker` o ottieni poi problemi in runtime?

**Comment by danyalberton** [comment]
> @ivanoalonzi probabile che l'errore sia dato dal fatto che non ho creato la classe App che estende Application che implementa Configuration.Provider ma ho delegato la main activity tutto il lavoro della creazione del Worker?

Esatto, il `Configuration.Provider` deve essere implementato dalla classe che estende `Application`.

**Comment by viseldev** [comment]
No @ivanoalonzi , non ottengo problemi runtime durante l'inizializzazione del Worker. Ho separato le due cose ma comunque non riesce ad istanziarmi il VerificationViewModel

**Comment by ivanoalonzi** [comment]
@viseldev, non so cosa dirti. A me funziona correttamente.
@danyalberton si se inserisco la chiamata inizializzo correttamente LoadKeysWorker. L'avevo rimossa per un test

**Comment by ivanoalonzi** [comment]
@viseldev , prova a creare la classe App perché devi marcarla con l'annotation HiltAndroidApp. Senza questo il meccanismo di Injection non credo funzioni

**Comment by viseldev** [comment]
@ivanoalonzi ho creato la classe App e in effetti ho un errore runtime durante la creazione del Worker. Creo un nuovo progetto basandomi sugli step del ministero

**Comment by ivanoalonzi** [comment]
Dopo una mattinata di madonne, ho domato la bestia. Green Pass verificato con sdk.
Ecco l'init della classe per la verifica del Green Pass
private void initVerificationObserver() {
        verificationViewModel = new ViewModelProvider(this).get(VerificationViewModel.class);
        Observer<CertificateSimple> certObserver = new Observer<CertificateSimple>(){
            @Override
            public void onChanged(CertificateSimple certificateSimple) {
                Log.i(TAG + "certObserver) ", certificateSimple.getCertificateStatus().toString());
            }
        };
        verificationViewModel.getCertificate().observe(this, certObserver);
        Observer<Boolean> inProgressObserver = new Observer<Boolean>() {
            @Override
            public void onChanged(Boolean aBoolean) {
                Log.i(TAG + "inProgressObserver) ", aBoolean.toString());
            }
        };
        verificationViewModel.getInProgress().observe(this, inProgressObserver);
    }

**Comment by viseldev** [comment]
Purtroppo non capisco dove sbaglio, anche ricreando il progetto daccapo ottengo questo:

E/WM-WorkerFactory: Could not instantiate it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker
    java.lang.NoSuchMethodException: it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker.<init> [class android.content.Context, class androidx.work.WorkerParameters]
        at java.lang.Class.getConstructor0(Class.java:2332)
        at java.lang.Class.getDeclaredConstructor(Class.java:2170)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:245)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
E/WM-WorkerWrapper: Could not create Worker it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker

**Comment by andrearavalli** [comment]
> Dopo una mattinata di madonne, ho domato la bestia. Green Pass verificato con sdk. Ecco l'init della classe per la verifica del Green Pass private void initVerificationObserver() { verificationViewModel = new ViewModelProvider(this).get(VerificationViewModel.class); Observer certObserver = new Observer(){ @OverRide public void onChanged(CertificateSimple certificateSimple) { Log.i(TAG + "certObserver) ", certificateSimple.getCertificateStatus().toString()); } }; verificationViewModel.getCertificate().observe(this, certObserver); Observer inProgressObserver = new Observer() { @OverRide public void onChanged(Boolean aBoolean) { Log.i(TAG + "inProgressObserver) ", aBoolean.toString()); } }; verificationViewModel.getInProgress().observe(this, inProgressObserver); }

grande! è troppo chiedere se ci puoi riassumere i passi per arrivarci in fondo?

**Comment by ivanoalonzi** [comment]
Io avevo un messaggio simile quando non ho seguito la guida. Quindi ho creato in Android Studio un progetto con Empty Activity e poi ho seguito gli step qui: (aggiungendo le dipendenze e copiando i file gradle). 
https://github.com/ministero-salute/it-dgc-verificac19-sdk-android

La situazione che abbiamo preso noi è usare un app java che invoca un sdk kotlin quindi è fondamentale che tutto l'environment sia corretto compreso quello kotlin.
Una vola creato il progetto come da guida devi aggiungere le annotation
AndroidEntryPoint nella MainActivity
e HiltAndroidApp sulla classe App (quella che estende Application) e che implementa Configuration.Provider

In questo modo a me funzionato tutto.

**Comment by andrearavalli** [comment]
> Io avevo un messaggio simile quando non ho seguito la guida. Quindi ho creato in Android Studio un progetto con Empty Activity e poi ho seguito gli step qui: (aggiungendo le dipendenze e copiando i file gradle). https://github.com/ministero-salute/it-dgc-verificac19-sdk-android
> 
> La situazione che abbiamo preso noi è usare un app java che invoca un sdk kotlin quindi è fondamentale che tutto l'environment sia corretto compreso quello kotlin. Una vola creato il progetto come da guida devi aggiungere le annotation AndroidEntryPoint nella MainActivity e HiltAndroidApp sulla classe App (quella che estende Application) e che implementa Configuration.Provider
> 
> In questo modo a me funzionato tutto.



> Io avevo un messaggio simile quando non ho seguito la guida. Quindi ho creato in Android Studio un progetto con Empty Activity e poi ho seguito gli step qui: (aggiungendo le dipendenze e copiando i file gradle). https://github.com/ministero-salute/it-dgc-verificac19-sdk-android
> 
> La situazione che abbiamo preso noi è usare un app java che invoca un sdk kotlin quindi è fondamentale che tutto l'environment sia corretto compreso quello kotlin. Una vola creato il progetto come da guida devi aggiungere le annotation AndroidEntryPoint nella MainActivity e HiltAndroidApp sulla classe App (quella che estende Application) e che implementa Configuration.Provider
> 
> In questo modo a me funzionato tutto.

Grazie mille, ci proverò

**Comment by viseldev** [comment]
Ok sono riuscito finalmente ad inizializzare il Worker correttamente. @ivanoalonzi seguendo i tuoi step con l'observer però, al momento in cui richiamo verificationModel.init(qrContent,false); ottengo una NullPointerException sul GSon:

java.lang.NullPointerException: Gson().fromJson(jsonStri… Array<Rule>::class.java) must not be null

I'm going to freak-out

**Comment by ivanoalonzi** [comment]
@viseldev ho lo stesso problema. Dipende da un file settings non inizializzato quindi fallisce il controllo sulla versione dell'sdk con quella ritornata dall'API REST.
Per il momento ho sostituito la funzione init con decode. La init fa il check delle versioni ed invoca decode.
Quando ho tempo capirò il perché e come risolvere.

Saluti

**Comment by sirol81** [comment]
> Dopo una mattinata di madonne, ho domato la bestia. Green Pass verificato con sdk. 

proverò a seguire i tuoi suggerimenti sperando di riuscirci anche io. grazie per aver condiviso App e MainActivity

**Comment by viseldev** [comment]
@ivanoalonzi esatto, è la stessa cosa che ho fatto io per farla funzionare. Del resto abbiamo anche un altro problema: ci hai fatto caso che se vai su Google Play e cerchi VerificaC19 risulta installata sul telefono quando non lo è? Nella scheda dello store appare il pulsante "Apri" e si apre la nostra app custom... Secondo me i programmatori del ministero dovrebbero creare una repository gradle unica per tutti e ampliare la documentazione, perché così la gente è costretta a prendere strade alternative e sicuramente rischiare di essere "non complient".

**Comment by viseldev** [comment]
@ivanoalonzi sta di fatto che anche scansionando un qr valido mi restitusce sempre che non è valido. Tutto questo sia rimpiazzando il metodo init col metodo decode, oppure semplicemente remmando la riga kotlin relativa al controllo dell'sdk version

**Comment by andrearavalli** [comment]
> @ivanoalonzi esatto, è la stessa cosa che ho fatto io per farla funzionare. Del resto abbiamo anche un altro problema: ci hai fatto caso che se vai su Google Play e cerchi VerificaC19 risulta installata sul telefono quando non lo è? Nella scheda dello store appare il pulsante "Apri" e si apre la nostra app custom... Secondo me i programmatori del ministero dovrebbero creare una repository gradle unica per tutti e ampliare la documentazione, perché così la gente è costretta a prendere strade alternative e sicuramente rischiare di essere "non complient".

no vabbè ma questa è fantastica..quello dello store intendo..siamo al delirio 🤣

**Comment by viseldev** [comment]
@andrearavalli è ovvio... riconosce il package uguale a quello di verificaC19! XD

**Comment by andrearavalli** [comment]
> @andrearavalli è ovvio... riconosce il package uguale a quello di verificaC19! XD

questo comunque fa già capire quanto questo codice NON SI POSSA USARE in quanto crea l'impossibilità di installare VerificaC19 se hai un app che usa l'SDK..

**Comment by ivanoalonzi** [comment]
@viseldev, probabilmente non ti funziona perché stai lavorando in debug. La modalità debug punta al server sogei che non va e quindi non ti scarica le chiavi. Per ora sostituisci le variabili 
BASE_URL
SERVER_HOST
CERTIFICATE_SHA
del buildTypes, debung con quelle di release.
in it-dgc-verificac19-sdk-android/sdk/build.gradle

**Comment by danyalberton** [comment]
> > @andrearavalli è ovvio... riconosce il package uguale a quello di verificaC19! XD
> 
> questo comunque fa già capire quanto questo codice NON SI POSSA USARE in quanto crea l'impossibilità di installare VerificaC19 se hai un app che usa l'SDK..

@andrearavalli Ovviamente la tua app dovrà avere un package diverso e potrà quindi coesistere con l'app VerficaC19 sullo stesso dispositivo.

**Comment by danyalberton** [comment]
> Purtroppo non capisco dove sbaglio, anche ricreando il progetto daccapo ottengo questo:
> 
> E/WM-WorkerFactory: Could not instantiate it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker java.lang.NoSuchMethodException: it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker. [class android.content.Context, class androidx.work.WorkerParameters] at java.lang.Class.getConstructor0(Class.java:2332) at java.lang.Class.getDeclaredConstructor(Class.java:2170) at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95) at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:245) at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137) at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:919) E/WM-WorkerWrapper: Could not create Worker it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker

Avevo lo stesso problema, ho risolto copiando per intero tutto il contenuto del `build.gradle` dell'App dal progetto di VerificaC19.
Probabilmente il problema era dovuto alla mancanza di qualche componente o qualche direttiva per Kotlin.

**Comment by ivanoalonzi** [comment]
@danyalberton il problema è l'environment. Copiando il build.gradle di VerificaC19 hai risolto.

**Comment by sirol81** [comment]
> @viseldev, probabilmente non ti funziona perché stai lavorando in debug. La modalità debug punta al server sogei che non va e quindi non ti scarica le chiavi. Per ora sostituisci le variabili BASE_URL SERVER_HOST CERTIFICATE_SHA del buildTypes, debung con quelle di release. in it-dgc-verificac19-sdk-android/sdk/build.gradle

grazie a questa dritta sono riuscito a far funzionare l'app VerificaC19 in debug (prima non funzionava come previsto, dicendo che doveva collegarsi almeno una volta alla rete per scaricare i certificati), ora la mia idea è di modificarla aggiungendo la business logic necessaria per comunicare il risultato della scansione internamente all'azienda, senza impazzire con la configurazione corretta dell'SDK che in questo modo è già bello e pronto!

**Comment by ivanoalonzi** [comment]
@sirol81 se non ci aiutiamo tra noi disgraziati sarebbe dura far funzionare questo sdk ridicolo

**Comment by ivanoalonzi** [comment]
@sirol81 il tuo approccio è quello che ho seguito io inizialmente ma non credo sia ottimale per questi motivi:
- Il ministero approva verifiche del green pass con verificaC19 ufficiale
- il ministero approva verifiche del green pass con app custom che si basano su sdk verificaC19
- Se escono modifiche ai controlli di VerificaC19, devi riprendere l'app dal repository e riportare tutte le tue modifiche all'interno dell'app custom

Con l'sdk, aggiorni il progetto, fail il nuovo build e rilasci la nuova release

Ivano

**Comment by sirol81** [comment]
> @sirol81 il tuo approccio è quello che ho seguito io inizialmente ma non credo sia ottimale per questi motivi:
> 
> * Il ministero approva verifiche del green pass con verificaC19 ufficiale
> * il ministero approva verifiche del green pass con app custom che si basano su sdk verificaC19
> * Se escono modifiche ai controlli di VerificaC19, devi riprendere l'app dal repository e riportare tutte le tue modifiche all'interno dell'app custom
> 
> Con l'sdk, aggiorni il progetto, fail il nuovo build e rilasci la nuova release
> 
> Ivano

sono d'accordo con te sul discorso in generale, ma nel caso specifico l'app VerificaC19 qui presente su github si basa su SDK esterno da clonare separatamente (nonostante abbia una sottocartella dgc-sdk, il settings.gradle punta a `project(':dgc-sdk').projectDir = new File("../it-dgc-verificac19-sdk-android/sdk")`
Così facendo, aggiungendo un paio di righe di codice per due chiamate REST in croce, ricado nel caso n.2 che hai elencato, ovvero una app custom (VerC19 leggermente modificata per i miei scopi) che usa SDK ufficiale.
Da un punto di vista delle tempistiche, ci ho messo molto meno ad aggiungere le chiamate all'app già funzionante che non i 3gg persi per capire come invocare correttamente l'SDK da una app costruita ex-novo. Anche in caso di modifiche sostanziali, credo che il tempo di reinserire le mie modifiche custom sarebbe relativamente breve.
Quando l'SDK sarà più maturo da un punto di vista della documentazione, magari ritenterò l'approccio originale.
Purtroppo ieri usando i tuoi App e MainActivity avevo errore in fase di deploy che non riusciva a risolvere un pacchetto "full.jar" mentre se procedevo a piccoli step, appena introducevo @androidEntryPoint mi crashava a runtime.
Quindi per ora sto personalizzando VerC19 presa per intero, che fortunatamente con il tuo trucchetto di cambiare puntamento da sogei al server di prod, funziona al primo tentativo! grazie ancora

**Comment by raffan83** [comment]
> Ok sono riuscito finalmente ad inizializzare il Worker correttamente. @ivanoalonzi seguendo i tuoi step con l'observer però, al momento in cui richiamo verificationModel.init(qrContent,false); ottengo una NullPointerException sul GSon:
> 
> java.lang.NullPointerException: Gson().fromJson(jsonStri… Array::class.java) must not be null
> 
> I'm going to freak-out

@viseldev scusa ma come hai risolto? perché io sono sempre fermo li, è come se la classe App non partisse, sto sviluppando in kotlin e per completezza posto il codice della classe App

@HiltAndroidApp
class App : Application() ,Configuration.Provider {



    @Inject
    lateinit var workerFactory: HiltWorkerFactory

    @Override
    override fun onCreate() {
        super.onCreate()
        setWorkManager()
    }

    @NonNull
    @Override
    override fun getWorkManagerConfiguration(): Configuration {
        return Configuration.Builder()
            .setWorkerFactory(workerFactory)
            .build()
    }

    private fun setWorkManager() {
        println("-- Worker MANAGER (YZMND)--")
        val uploadWorkRequest: WorkRequest =
            PeriodicWorkRequestBuilder<LoadKeysWorker>(1, TimeUnit.DAYS)
                .setConstraints(
                    Constraints.Builder()
                        .setRequiredNetworkType(NetworkType.CONNECTED)
                        .build()
                )
                .build()
        WorkManager
            .getInstance(this)
            .enqueueUniquePeriodicWork(
                "LoadKeysWorker",
                ExistingPeriodicWorkPolicy.REPLACE,
                uploadWorkRequest as PeriodicWorkRequest
            )
    }
}

la stringa "-- Worker MANAGER (YZMND)--" non la vedo sulla console, credo che l'Inject non funziona.
Qualcuno ha qualche suggerimento, Grazie 1000

**Comment by PaoloG1980** [comment]
Buona sera a tutti, sto sviluppando un app in kotlin e quando cerco di istanziare la classe VerificationViewModel mi da errore.
Per istanziare la classe uso questo codice:
**_**var viewModel = ViewModelProvider(this).get(VerificationViewModel::class.java)**_**
ma quando vado in run mi da questo errore:
**_java.lang.RuntimeException: Cannot create an instance of class it.ministerodellasalute.verificaC19sdk.model.VerificationViewModel_**

qualcuno sa come risolvere???
Grazie Paolo

**Comment by sirol81** [comment]
> Buona sera a tutti, sto sviluppando un app in kotlin e quando cerco di istanziare la classe VerificationViewModel mi da errore. Per istanziare la classe uso questo codice: **_**var viewModel = ViewModelProvider(this).get(VerificationViewModel::class.java)**_** ma quando vado in run mi da questo errore: **_java.lang.RuntimeException: Cannot create an instance of class it.ministerodellasalute.verificaC19sdk.model.VerificationViewModel_**
> 
> qualcuno sa come risolvere??? Grazie Paolo

avevo anche io questo errore, pare che la soluzione sia nel decorare la classe con @androidEntryPoint ma se lo facevo mi crashava tutto a runtime. Trovi dei commenti al riguardo anche nelle altre issues, cerca quelle con "@androidEntryPoint"
Io personalmente attendo tempi migliori, nel frattempo ho modificato direttamente l'app VerificaC19 (il cui repository si trova sempre ufficialmente fra quelli del ministero)

**Comment by Y2JChamp** [comment]
> > Purtroppo non capisco dove sbaglio, anche ricreando il progetto daccapo ottengo questo:
> > E/WM-WorkerFactory: Could not instantiate it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker java.lang.NoSuchMethodException: it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker. [class android.content.Context, class androidx.work.WorkerParameters] at java.lang.Class.getConstructor0(Class.java:2332) at java.lang.Class.getDeclaredConstructor(Class.java:2170) at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95) at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:245) at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137) at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:919) E/WM-WorkerWrapper: Could not create Worker it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker
> 
> Avevo lo stesso problema, ho risolto copiando per intero tutto il contenuto del `build.gradle` dell'App dal progetto di VerificaC19. Probabilmente il problema era dovuto alla mancanza di qualche componente o qualche direttiva per Kotlin.

confermo che così sono riuscito anche io

**Comment by PaoloG1980** [comment]
> > > Purtroppo non capisco dove sbaglio, anche ricreando il progetto daccapo ottengo questo:
> > > E/WM-WorkerFactory: Could not instantiate it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker java.lang.NoSuchMethodException: it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker. [class android.content.Context, class androidx.work.WorkerParameters] at java.lang.Class.getConstructor0(Class.java:2332) at java.lang.Class.getDeclaredConstructor(Class.java:2170) at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95) at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:245) at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137) at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:919) E/WM-WorkerWrapper: Could not create Worker it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker
> > 
> > 
> > Avevo lo stesso problema, ho risolto copiando per intero tutto il contenuto del `build.gradle` dell'App dal progetto di VerificaC19. Probabilmente il problema era dovuto alla mancanza di qualche componente o qualche direttiva per Kotlin.
> 
> confermo che così sono riuscito anche io

Scusa ma che file build.gradle hai copiato quello del modulo dell'app oppure quello dell'intero progetto?.
Grazie in anticipo

**Comment by danyalberton** [comment]
@PaoloG1980 devi copiare il file `build.gradle` dell'App. Su quello del progetto devi eventualmente copiare le dipendenze mancanti.
Facendo così anch'io sono riuscito a compilare e eseguire la verifica di Green Pass (fatto con progetto Java).

**Comment by PaoloG1980** [comment]
> @PaoloG1980 devi copiare il file `build.gradle` dell'App. Su quello del progetto devi eventualmente copiare le dipendenze mancanti. Facendo così anch'io sono riuscito a compilare e eseguire la verifica di Green Pass (fatto con progetto Java).

Ok fatto come dici e adesso pare funzionare, mi legge il _LoadKeysWorker_.
Adesso sono fermo nell'istanziare il VerificationViewModel.

io ho usato questo codice
_viewModel = ViewModelProvider(this).get(VerificationViewModel::class.java)_

ma mi restituisce errore:
_java.lang.RuntimeException: Cannot create an instance of class it.ministerodellasalute.verificaC19sdk.model.VerificationViewModel_

**Comment by danyalberton** [comment]
@PaoloG1980 probabilmente devi solo aggiungere il tag `@AndroidEntryPoint` nell'activity in cui stai instanziando il VerificationViewModel.
Puoi prendere spunto dal codice della **MainActivity()** condivisa da @ivanoalonzi qui:
https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/issues/42#issuecomment-947505882

**Comment by BlackHoleVR** [comment]
Ciao a tutti, dopo aver inizilizzato il WorkManager eseguo il seguente metodo:

**viewModel.init(itTestQr, true)** 

che ritorna la seguente exception : **java.lang.NullPointerException: Gson().fromJson(jsonStri… Array<Rule>::class.java) must not be null**

X favore, qualcuno sa come risolvere? Grazie a tutti e ciaooo

**Comment by raffan83** [comment]
> Ciao a tutti, dopo aver inizilizzato il WorkManager eseguo il seguente metodo:
> 
> **viewModel.init(itTestQr, true)**
> 
> che ritorna la seguente exception : **java.lang.NullPointerException: Gson().fromJson(jsonStri… Array::class.java) must not be null**
> 
> X favore, qualcuno sa come risolvere? Grazie a tutti e ciaooo

Ciao @BlackHoleVR devi utilizzare il metodo decode anzichè init. init controlla la versione dell sdk per questo non funziona, decode è identico ma non esegue questo controllo. Ma per istanziare l'oggetto hai eseguito le indicazioni già note oppure hai fatto qualche altra cosa perchè a me continua a dare ClassCastExcep..

**Comment by PaoloG1980** [comment]
A questo punto credo di essermi rincoglionito: ero convinto di essere riuscito a istanziare correttamente il workmanger, ho provato anche a mettere il blocco di istruzioni tra try/catch senza mai intecettare nessu excption... poi mi capita di scorrere il LogCat e trovo questo errore :
_E/WM-WorkerFactory: Could not instantiate it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker
    java.lang.NoSuchMethodException: <init> [class android.content.Context, class androidx.work.WorkerParameters]
        at java.lang.Class.getConstructor0(Class.java:2204)
        at java.lang.Class.getDeclaredConstructor(Class.java:2050)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:245)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
2021-10-22 15:24:32.299 19027-19055/com.example.appgp E/WM-WorkerWrapper: Could not create Worker it.ministerodellasalute.verificaC19sdk.worker.LoadKeysWorker_
ma in esecuzione l'app so crea correttamente e non mi da nessun crash, pero quando cerco di fare l'istanza del VerificationViewModel mi da errore e l'app va in crash....
Ora suppongo che le due cose siano collegate, ma non so proprio come uscire da questo ginepraio...
Qualcuno sa come aiutarmi..... o magari caricare un progetto con Workmanager e VerificationViewModel gia istanziati e funzionanti...vi prego
Grazie a tutti

**Comment by ivanoalonzi** [comment]
@PaoloG1980  
Devi mettere le annotation 
\@AndroidEntryPoint sulla main activity
e 
\@HiltAndroidApp
sulla classe che estende Application
Guardalo sui file che ho allegato qualche commento fa

Saluti

**Comment by PaoloG1980** [comment]
@ivanoalonzi 
Ho gia messo le due annotation ma non funziona

**Comment by BlackHoleVR** [comment]
> > Ciao a tutti, dopo aver inizilizzato il WorkManager eseguo il seguente metodo:
> > **viewModel.init(itTestQr, true)**
> > che ritorna la seguente exception : **java.lang.NullPointerException: Gson().fromJson(jsonStri… Array::class.java) must not be null**
> > X favore, qualcuno sa come risolvere? Grazie a tutti e ciaooo
> 
> Ciao @BlackHoleVR devi utilizzare il metodo decode anzichè init. init controlla la versione dell sdk per questo non funziona, decode è identico ma non esegue questo controllo. Ma per istanziare l'oggetto hai eseguito le indicazioni già note oppure hai fatto qualche altra cosa perchè a me continua a dare ClassCastExcep..

Ciao Raffan e grazie il metodo decode funziona ritorna correttamente tutti i miei dati anagrafici ma il certificato risulta **non valido**.
Per il tuo problema io ho fatto così:
1 - Crea una nuova applicazione EmptyActivity seguendo le nuove note descritte nel progetto SDK e cerca di compilarla ed eseguirla così com'è.
2 - Poi crea la Classe VerificaApplication che deriva da Application x instanzire il WorkManagaer (copiala dall'esempio **it-dgc-verificaC19-android**)
3 - Poi usa la tua mainActivity usando il metodo che mi hai detto... Devi mettere l'annotation @AndroidEntryPoint

**Comment by PaoloG1980** [comment]
Buongiornoa  tutti.
Sto cercando di usare la funzione decode prendendo spunto da quanto fatto da @ivanoalonzi  nel suo file MainActivity,
ma quando vado a richiamare il metodo _getCertificate_ non me lo riconosce.
Entrando nella classe  _VerificationViewModel_ effettivmente questo metodo non c'e, ma cercando nella documentazione ufficiale esiste. Qualcuno sa come risolvere?
Grazie Paolo

**Comment by GabrieleCicconetti** [comment]
Confermo che non funziona aggiungendo `@AndroidEntryPoint` a MainActivity continua a dare

`java.lang.ClassCastException: it.ministerodellasalute.verificaC19sdk.DaggerVerificaApplication_HiltComponents_SingletonC$ActivityRetainedCImpl$ActivityCImpl cannot be cast to com.company.app.MainActivity_GeneratedInjector`


Update:

Per chi avesse questo problema ho cercato di esporre la soluzione che per me ha funzionato qui -> https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/issues/70
