### ISSUE TITLE
Certificato non valido

### ISSUE THREAD

**Issue by Y2JChamp** [ministero-salute/it-dgc-verificac19-sdk-android#49]
Ad integrazione della libreria completata, quando invio il qr code del mio green pass (valido), l'oggetto CertificateSimple è correttamente compilato coi miei dati anagrafici, ma l'oggetto CertificateStatus è valorizzato "NOT_VALID".
Ho provato con l'app di verifica standalone VerificaC19 installata dall'App Store e il mio certificato è giustamente valido.

**Comment by acaliaro** [comment]
non so se può dipendere da questo https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/issues/42#issuecomment-947766050

**Comment by Y2JChamp** [comment]
avevo già fatto quella modifica, ma nulla:
 debug {
            minifyEnabled false
            buildConfigField "String", "BASE_URL", "\"https://get.dgc.gov.it/v1/dgc/\""
            buildConfigField "String", "SERVER_HOST", "\"get.dgc.gov.it\""
            buildConfigField "String", "CERTIFICATE_SHA", "\"sha256/7cZJIDPacG8FS3pq6Mvxg+7yBDM/VYc2alOcbVe/e74=\""
            buildConfigField "String", "SDK_VERSION", "\"1.0.0\""
        }

La cosa particolare è che mi ritorna nome, cognome e data di nascita giusti...

**Comment by Y2JChamp** [comment]
fallisce in getCertificate alla seguente istruzione:
val key = db.keyDao().getById(kid)

la key è null dopo quella istruzione

**Comment by VincenzoCanfora** [comment]
Se può essere di aiuto noi abbiamo risolto il problema dalla funzione SDK.

Classe VerifierRepositoryImpl all'interno della funzione fetchCertificate, abbiamo aggiunto un semplice contatore esterno ed un controllo su HTTP_BAD_GATEWAY.

        var chek = 0.toLong()
        private suspend fun fetchCertificate(resumeToken: Long) {
        val tokenFormatted = if (resumeToken == -1L) "" else resumeToken.toString()
        val response = apiService.getCertUpdate(tokenFormatted)
        if (response.isSuccessful && response.code() == HttpURLConnection.HTTP_OK) {
        val headers = response.headers()
        val responseKid = headers[HEADER_KID]
        val newResumeToken = headers[HEADER_RESUME_TOKEN]
        val responseStr = response.body()?.stringSuspending(dispatcherProvider) ?: return

        if (validCertList.contains(responseKid)) {
            Log.i(VerifierRepositoryImpl::class.java.simpleName, "Cert KID verified")
            val key = Key(kid = responseKid!!, key = keyStoreCryptor.encrypt(responseStr)!!)
            db.keyDao().insert(key)

            preferences.resumeToken = resumeToken

            newResumeToken?.let {
                var newToken = it.toLong()
                chek = it.toLong()
                fetchCertificate(newToken)
            }
        }
    }else if (response.code() == HttpURLConnection.HTTP_BAD_GATEWAY) {
        chek = chek+1.toLong();
        var newToken = chek;

        fetchCertificate(newToken)
    }
}
Ovviamente è una forzatura ma almeno permette di scaricare la maggiorn parte dei certificati.

**Comment by Y2JChamp** [comment]
> Se può essere di aiuto noi abbiamo risolto il problema dalla funzione SDK.
> 
> Classe VerifierRepositoryImpl all'interno della funzione fetchCertificate, abbiamo aggiunto un semplice contatore esterno ed un controllo su HTTP_BAD_GATEWAY.
> 
> ```
>     var chek = 0.toLong()
>     private suspend fun fetchCertificate(resumeToken: Long) {
>     val tokenFormatted = if (resumeToken == -1L) "" else resumeToken.toString()
>     val response = apiService.getCertUpdate(tokenFormatted)
>     if (response.isSuccessful && response.code() == HttpURLConnection.HTTP_OK) {
>     val headers = response.headers()
>     val responseKid = headers[HEADER_KID]
>     val newResumeToken = headers[HEADER_RESUME_TOKEN]
>     val responseStr = response.body()?.stringSuspending(dispatcherProvider) ?: return
> 
>     if (validCertList.contains(responseKid)) {
>         Log.i(VerifierRepositoryImpl::class.java.simpleName, "Cert KID verified")
>         val key = Key(kid = responseKid!!, key = keyStoreCryptor.encrypt(responseStr)!!)
>         db.keyDao().insert(key)
> 
>         preferences.resumeToken = resumeToken
> 
>         newResumeToken?.let {
>             var newToken = it.toLong()
>             chek = it.toLong()
>             fetchCertificate(newToken)
>         }
>     }
> }else if (response.code() == HttpURLConnection.HTTP_BAD_GATEWAY) {
>     chek = chek+1.toLong();
>     var newToken = chek;
> 
>     fetchCertificate(newToken)
> }
> ```
> 
> } Ovviamente è una forzatura ma almeno permette di scaricare la maggiorn parte dei certificati.

non credo sia quello il problema, ho questa eccezione:
2021-10-22 16:05:01.042 14596-14629/it.wakala.smartgreenpass.mobile I/LoadKeysWorker: key fetching start
2021-10-22 16:05:01.042 14596-14629/it.wakala.smartgreenpass.mobile V/BaseRepository: Do network coroutine work
2021-10-22 16:05:01.044 14596-14629/it.wakala.smartgreenpass.mobile I/reenpass.mobil: Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.platform.Platform>: java.lang.ExceptionInInitializerError: 
    (Throwable with no stack trace)
2021-10-22 16:05:01.045 14596-14629/it.wakala.smartgreenpass.mobile W/BaseRepository: Throwable
    java.lang.NoClassDefFoundError: okhttp3.internal.platform.Platform
        at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:944)

Ho provato anche ad importare okhttp nel gradle ma nulla

**Comment by Y2JChamp** [comment]
importando questa lib okttp le chiamate di rete vanno:
    implementation 'com.squareup.okhttp3:okhttp:4.2.2'

**Comment by Y2JChamp** [comment]
risolto:
oltre la libreria okttp importata nel gradle dell'sdk e della mia app, ho aggiunto il controllo suggerito da @VincenzoCanfora .

Chiudo

**Comment by PaoloG1980** [comment]
@Y2JChamp ho anche io il problema del Certificato non valido:
Ho modificato le variabili di debug con il valore di quelle di release
Ho modificato il codice della funzione fetchCertificate
Ho aggiunto nel build.gradle della mia app e nel build.gradle dell'sdk la dipendenza: implementation 'com.squareup.okhttp3:okhttp:4.2.2'
ma ancora mi da certificato non valido...
ho perso o sbagliato qualche passaggio???

**Comment by PaoloG1980** [comment]
@Y2JChamp , ho risolto avevo sbagliato a modificare le variabili di debug.
Adesso funziona , grazie cmq.
Ciao Paolo
