### ISSUE TITLE
Bug con Android 11 e Android 12 su progetti con targetSdkVersion 30

### ISSUE THREAD

**Issue by danyalberton** [ministero-salute/it-dgc-verificac19-sdk-android#59]
**Descrizione del bug**
Aggiornando il nostro progetto che integra l'SDK di VerificaC19 al targetSdkVersion 30 (obbligatorio per poter caricare aggiornamenti e nuove app sul Play Store a partire dal 1 Novembre scorso) l'App va in crash e genera il seguente errore a runtime:
#### AndroidPlatform.kt line 370:   okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported
```
Caused by java.lang.IllegalStateException
Expected Android API level 21+ but was 30
```

**Riproduzione del bug**
1. Aggiornare il target SDK alla versione 30
2. Implementare altre librerie che fatto uso della libreria **com.squareup.okhttp3** (ad esempio Firebase Crashlytics, vedi screen sotto)
3. Eseguire l'app e utilizzare una funzione che richieda l'utilizzo della libreria **com.squareup.okhttp3**

**Problema riscontrato**

L'app va in crash.

**Screenshots**

<img width="785" alt="Bug with target SDK 30" src="https://user-images.githubusercontent.com/26014916/140764429-84fc956e-c95c-4cc8-806e-2db64e179daa.png">

**Smartphone**
 - Device: tutti i dispositivi con Android 11 e Android 12
 - OS: Android 11, Android 12

**Soluzione**
La soluzione consiste nell'aggiornare la libreria **com.squareup.okhttp3:logging-interceptor** dalla versione 4.0.1 (utilizzata nei progetti dell'SDK) alla più recente versione 4.9.2.

**Richiesta**
Chiedo pertanto che vengano adeguati tutti i progetti necessari all'esecuzione dell'SDK alla più recente versione Target dell'SDK di Android, così da poter essere utilizzati senza generare bug.

**Comment by loreberti89** [comment]
Brutte cose...si leggono queste cose troppo tardi..   :,( A me non crasha, ma non valida i greenpass.
Mentre la solita app con android 10 si.

**Comment by andrearavalli** [comment]
Beh cambiando il target dell'SDK credo sia normale dover aggiornare le librerie usate no?
In teoria essendo una "pseudo" SDK non bisognerebbe toccare nulla

**Comment by loreberti89** [comment]
> **Descrizione del bug** Aggiornando il nostro progetto che integra l'SDK di VerificaC19 al targetSdkVersion 30 (obbligatorio per poter caricare aggiornamenti e nuove app sul Play Store a partire dal 1 Novembre scorso) l'App va in crash e genera il seguente errore a runtime:
> 
> #### AndroidPlatform.kt line 370: okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported
> ```
> Caused by java.lang.IllegalStateException
> Expected Android API level 21+ but was 30
> ```
> 
> **Riproduzione del bug**
> 
> 1. Aggiornare il target SDK alla versione 30
> 2. Implementare altre librerie che fatto uso della libreria **com.squareup.okhttp3** (ad esempio Firebase Crashlytics, vedi screen sotto)
> 3. Eseguire l'app e utilizzare una funzione che richieda l'utilizzo della libreria **com.squareup.okhttp3**
> 
> **Problema riscontrato**
> 
> L'app va in crash.
> 
> **Screenshots**
> 
> <img alt="Bug with target SDK 30" width="785" src="https://user-images.githubusercontent.com/26014916/140764429-84fc956e-c95c-4cc8-806e-2db64e179daa.png">
> 
> **Smartphone**
> 
> * Device: tutti i dispositivi con Android 11 e Android 12
> * OS: Android 11, Android 12
> 
> **Soluzione** La soluzione consiste nell'aggiornare la libreria **com.squareup.okhttp3:logging-interceptor** dalla versione 4.0.1 (utilizzata nei progetti dell'SDK) alla più recente versione 4.9.2.
> 
> **Richiesta** Chiedo pertanto che vengano adeguati tutti i progetti necessari all'esecuzione dell'SDK alla più recente versione Target dell'SDK di Android, così da poter essere utilizzati senza generare bug.

La soluzione da te descritta funziona.
Grazie mille!
