### ISSUE TITLE
BlackList non funzionante

### ISSUE THREAD

**Issue by bobbysimon24** [ministero-salute/it-dgc-verificac19-sdk-android#65]
Ciao a tutti, premetto che son abbastanza nuovo sull'argomento avendo cominciato a programmare su android con questa app.
Finalmente dopo qualche giorno di scleri sono riuscito a compilare e far partire l'sdk. Funziona la scansione e tutto ma la blacklist non va. Inizialmente ho notato che dentro al VerificationViewModel quando viene lanciata la funzione decode() utilizza due variabili diverse di CertificateSimple() per salvarsi i risultati dell'elaborazione (certificateSimple e simpleCert). Vengono poi utilizzati due metodi diversi per verificare le blacklist (Almeno da quanto ho capito), il primo da praticamente tutti i green pass come revocati, visto che da quel che mi sembra fa un controllo sui certificati (Che se non mi sbaglio "contengono" milioni di GreenPass l'uno), mentre il secondo (E anche quello impostato di default) non mi funziona, me li da tutti come validi, anche quello famoso di Hitler.
Non capisco se la blacklist me la scarica correttamente, me la trovo nel database ma mi sembra che sia solo quella utilizzata dal primo metodo, ma non dal secondo, il quale da quel che ho capito utilizza Realm anzichè Room per salvare i dati, quindi mi verrebbe da dire che potrebbe essere che non la scarichi proprio la blacklist utilizzata dal secondo metodo, e in questo modo che mi dia appunto tutti i green pass come validi.
Qualcuno saprebbe darmi una mano o anche solo informazioni per venirne a capo?

**Comment by rawmain** [comment]
Ciao @bobbysimon24 

> Non capisco se la blacklist me la scarica correttamente, me la trovo nel database ma mi sembra che sia solo quella utilizzata dal primo metodo, ma non dal secondo, il quale da quel che ho capito utilizza Realm anzichè Room per salvare i dati, quindi mi verrebbe da dire che potrebbe essere che non la scarichi proprio la blacklist utilizzata dal secondo metodo, e in questo modo che mi dia appunto tutti i green pass come validi.

Attuale codice WIP nelle branch develop & feature DGC-SDK prevede :

- **black_list_uvci** = counterfeit/fraudulent UVCI presenti in chiaro nel JSON delle [Validation Rules](https://get.dgc.gov.it/v1/dgc/settings). 
-> _Attivo da prodrelease DGC-SDK 1.0.2 (ved. prodrelease 1.1.6 e 1.1.7 di VerificaC19 Android - pubblicate su Google PlayStore / Huawei AppGallery)._

- **CRL - RevokeList/RevokedPass** = revoked UVCI presenti come hash SHA-256 codificati base64 nei chunk scaricati da endpoint CRL (ved. [Apiservice.kt](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/blob/develop/sdk/src/main/java/it/ministerodellasalute/verificaC19sdk/data/remote/ApiService.kt)).
-> _CRL endpoint per status check & download chunk **NON ancora accessibili da chiunque** , ma solo da team ufficiale / utenti autorizzati._

Pertanto, è normale che al momento tu non veda ancora avvenire il download dei chunk con revoked insertions/deletions = le response alle request per CRL status e download restituiscono ancora code HTTP 403 Forbidden per connessioni da IP sorgente non autorizzati (ved. debug e logcat).

**Comment by bobbysimon24** [comment]
Caio @rawmain 

Grazie mille, molto utile, mi sembrava che fosse così in effetti ma non avevo modo di verificarlo al 100%.
Scusa di nuovo l'ignoranza ma da dove le hai trovate queste informazioni? Ho cercato davvero dappertutto ma non ho trovato queste che mi hai copiato (Sono nuovo anche su github ovviamente).
Inoltre vorrei capire, è normale quindi che se lascio le apk così come sono mi da tutti i green pass validi al momento? Perchè guardando anche solo l'identificativo di Hitler è presente nella blacklist in chiaro, mentre guardando il mio green pass valido non lo trovo nella lista, ma mi da comunque Green Pass non valido a me se uso certificateSimple anzichè simpleCert, che è quello di default impostato nelle apk.

**Comment by rawmain** [comment]
Ciao @bobbysimon24 

> Grazie mille, molto utile, mi sembrava che fosse così in effetti ma non avevo modo di verificarlo al 100%. 

Prego ;) .

> dove le hai trovate queste informazioni? 

Info visibili pubblicamente dall'osservazione di commit ultimi 30gg & status codice (in lavorazione) nelle active branch pubbliche develop/* e feature/* x DGC-SDK e verifier-app Android.

> è normale quindi che se lascio le apk così come sono mi da tutti i green pass validi al momento?

E' normale che _si rompa_ il flusso di validazione, visto che non stai compilando il codice in branch release, bensì il codice WIP (_ancora in lavorazione_) in branch develop & senza poter ancora scaricare correttamente i CRL revoke chunk.

In ambito di test correnti con codice branch develop/feature è possibile ripristinare un corretto flusso di validazione, impostando temporaneamente l'uso di mock JSON per CRL status e revokelist.

[Questo](https://gist.github.com/rawmain/37c68a3f6bc1fd1008b62d0dcbd5a80f) è p.es. uno dei miei test-chunk, che riprende le 135 entry attualmente in black_list_uvci + 2 test-sample QA addizionali -> si implementa agevolmente per ottenere build-variant release basate su codice develop & con OK flusso validazione ([sample](https://github.com/VC19rvk/it-dgc-verificaC19-android-RVK/releases/tag/1.1.7-RVK-20211116-Develop)).
 
- Modifica in it-dgc-verificac19-sdk-android/sdk/build.gradle

```
         release {
            buildConfigField "String", "BASE_URL", "\"https://get.dgc.gov.it/v1/dgc/\""
            buildConfigField "String", "BASE_URL_CRL", "\"https://gist.githubusercontent.com/rawmain/37c68a3f6bc1fd1008b62d0dcbd5a80f/raw/cc3d1ba88c0d4f755f399270d44e06bd9f07848b/rvktest01.json\""
            buildConfigField "String", "BASE_URL_CRL_REVOKES", "\"https://gist.githubusercontent.com/rawmain/37c68a3f6bc1fd1008b62d0dcbd5a80f/raw/cc3d1ba88c0d4f755f399270d44e06bd9f07848b/rvktest01.json\""
            buildConfigField "String", "SERVER_HOST", "\"get.dgc.gov.it\""
            buildConfigField "String", "CERTIFICATE_SHA", "\"sha256/7cZJIDPacG8FS3pq6Mvxg+7yBDM/VYc2alOcbVe/e74=\""
            buildConfigField "String", "SDK_VERSION", "\"1.0.3\""

            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
```

- Modifica in it-dgc-verificac19-sdk-android/sdk/src/main/java/it/ministerodellasalute/verificaC19sdk/data/remote/ApiService.kt

```
    /** @GET("drl/check") */
    @GET(BuildConfig.BASE_URL_CRL)
    suspend fun getCRLStatus(@Query("version") version: Long?): Response<ResponseBody>

    /** @GET("drl") */
    @GET(BuildConfig.BASE_URL_CRL_REVOKES)
    suspend fun getRevokeList(@Query("version") version: Long?, @Query("chunk") chunk: Long?, ): Response<ResponseBody>
```

**Comment by bobbysimon24** [comment]
Ok, grazie mille di nuovo, davvero.
Mi hai risparmiato diversi giorni di studio e approfondimento probabilmente, visto che erano dettagli che mi ero perso essendo per me nuovo github, ora ha tutto molto più senso.
👍 👍
