### ISSUE TITLE
[question] Super GreenPass

### ISSUE THREAD

**Issue by peppev-citel** [ministero-salute/it-dgc-verificac19-sdk-android#71]
Salve,
con l'introduzione del nuovo Super Green Pass ci saranno modifiche sostanziali all'attuale SDK, oppure potrà essere possibile utilizzare quella già pubblicata? A livello tecnico, in base a cosa sarà possibile distinguere un Green Pass da un Super Green Pass?

**Comment by Y2JChamp** [comment]
Mi aggrego alla domanda, l'idea che mi sono fatto è che ci sarà un esito specifico da API Rest che comunque andrà mappato in app.

**Comment by DevPGS** [comment]
guardando [qui ](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/commit/d0a3da2a0256a24ae4e32b039484436619e4a835) dovrebbe essere possibile passare un parametro aggiuntivo alla funzione di decode:
2G -> "super" green pass
3G -> green pass classico

anche osservando il codice dell'app android si vede che è stato aggiunto un "flag" all'app per la tipologia di greenpass da scansionare (https://github.com/ministero-salute/it-dgc-verificaC19-android/commit/b2ef873b9a763cf21086f3faa6f27d15e12a139f).

**Comment by rawmain** [comment]
Ciao @peppev-citel 

> con l'introduzione del nuovo Super Green Pass ci saranno modifiche sostanziali all'attuale SDK, oppure potrà essere possibile utilizzare quella già pubblicata?

L'attuale prodrelease 1.0.2 non supporta né la differenziazione dei flussi di validazione in funzione di scenario/tipologia di verifica (_3G Vaccinazione/Guarigione/Test - 2G Vaccinazione/Guarigione_) né l'utilizzo di CRL/DRL al posto di black_list_uvci in Validation Rules per i controlli di filtro.

Pertanto, a partire dal 6 Dicembre anche le app/soluzioni terze - in conformità ai requisiti di conformità ex artt. 12-13 DPCM 12/10/2021 - dovranno comunque usare la nuova prodrelease DGC-SDK Android/Kotlin.

Le modifiche lato DGC-SDK per supporto scenari 2G/3G sono state finalizzate 5gg fa, per cui - in attesa del rilascio nuova prodrelease (ved. [release-tracker](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/releases)) - è già possibile effettuare attività test/staging preliminari per integrazione nuovo codice DGC-SDK in app/soluzioni terze : 

- **Test SDK 1.0.2 black_list_uvci + scan-mode 2G/3G** = merge codice branch [release/1.0.2](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/release/1.0.2) +  [feature/super-dgp-sdk](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/feature/super-dgp-sdk)

- **Test SDK 1.0.3 CRL/DRL + scan-mode 2G/3G** = merge codice branch [develop](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/develop) +  [feature/super-dgp-sdk](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/feature/super-dgp-sdk) & mock temporanei per CRL API (ved. [note per test-chunk](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/issues/69#issuecomment-982744311))

--------------------------

> A livello tecnico, in base a cosa sarà possibile distinguere un Green Pass da un Super Green Pass?

Non vi è nessuna distinzione evidente / esplicitata lato UI - anche in conformità alle indicazioni GPDP.

Semplicemente, impostando 2G come scenario/tipologia di verifica, le scansioni di QR DGC con mapping T (sia PCR che RAT) restituiscono sempre esito NOT_VALID.
