### ISSUE TITLE
Definizione di guariti rispetto a 2G e 3G

### ISSUE THREAD

**Issue by lorenzob** [ministero-salute/it-dgc-verificac19-sdk-android#72]
Mi scuso per la domanda non tecnica ma probabilmente siete gli unici in grado di fare un po' di chiarezza su questo punto.

Cosa si intende per guariti rispetto a 2G e 3G?

Per i guariti con 1 dose la durata quant'e', 2G e 3G?

Per i guariti senza nessuna dose  la durata quant'e', 2G e 3G'?

Si parla di 9 mesi per i guariti, ma a partire dalla data di tampone positivo o di emissione? Per tutti o solo per chi ha la prima dose?

Il "recovery_cert_end_day" dentro verification_rules_success_response.json passera' a 270?

Sto guardando il codice ma per ora non vedo modifiche relative a questa parte.

Grazie

**Comment by rawmain** [comment]
Ciao @lorenzob 

> Cosa si intende per guariti rispetto a 2G e 3G?

Lo switch scenario/tipologia di verifica non cambia i flussi di validazione per le scansioni di QR DGC con mapping V (Vaccinazione) e R (Guarigione), ma solo quello per T (Test - Tamponi PCR e RAT) : 

- Scan Mode 3G (Vaccinazione/Guarigione/Test) -> esito validazione V/R/T in funzione di controllo firma + validation rules

- Scan Mode 2G (Vaccinazione/Guarigione) -> esito validazione V/R in funzione di controllo firma + validation rules, mentre per T si ha sempre esito NOT_VALID
 
> Per i guariti con 1 dose la durata quant'e', 2G e 3G? [...]

I valori start/end dei vari mapping V/R/T sono definiti chiaramente nel JSON delle [Validation Rules](https://get.dgc.gov.it/v1/dgc/settings), che il dispositivo di verifica recupera & aggiorna tramite fetch/sync all'avvio & periodicamente (periodo base/max 24h).

Pertanto, l'aggiornamento dei valori in Validation Rules avverrà inizialmente entro le 24h precedenti al 6 Dicembre e poi entro le 24h precedenti al 15 Dicembre , onde consentire ai dispositivi di verifica di effettuare le scansioni con l'app aggiornata per scan mode 2G/3G & recuperare appunto le nuove impostazioni di durata.

**Comment by bobbysimon24** [comment]
Quindi per capirci bene, un'applicazione che verifica il GreenPass dal 6 dicembre in poi dovrà avere due modalità? Una 2G che serve per verificare i "**Super Green Pass**" e una 3G che serve per verificare quelli "**Base**"?

**Comment by lorenzob** [comment]
Ciao @rawmain e grazie per la risposta.

La mia domanda allora si puo' riformulare in questo modo: e' possibile vedere gia' da ora quali saranno le validation rules dal 6 dicembre? Il file sara' uguale a quello sul branch super-dgp-sdk sotto test/assets? O lo trovo in un altro progetto?

Le validation rules sono le stesse sia per la modalita' 2G e 3G? In pratica l'unica differenza 2G/3G sarebbe l'esclusione dei tamponi?

**Comment by rawmain** [comment]
Ciao @bobbysimon24 

> Quindi per capirci bene, un'applicazione che verifica il GreenPass dal 6 dicembre in poi dovrà avere due modalità? Una 2G che serve per verificare i "**Super Green Pass**" e una 3G che serve per verificare quelli "**Base**"?

Corretto.

Le soluzioni/app terze, che utilizzano DGC-SDK Android/Kotlin, devono essere allineate con gli aggiornamenti codice - come previsto dai requisiti di conformità artt. 12-13 DPCM 12/10/2021.

Pertanto, dal 6 Dicembre anche le app/soluzioni terze conformi dovranno comunque consentire lato loro interfaccia/UI l'impostazione di scenario/tipologia di verifica da parte dell'operatore, in modo appunto da gestire correttamente le validazioni in funzione del valore preference/prefkey per scan mode 2G o 3G.

**Comment by rawmain** [comment]
Ciao @lorenzob 

> grazie per la risposta.

Prego ;).

> e' possibile vedere gia' da ora quali saranno le validation rules dal 6 dicembre?

No, visto che saranno vigenti dal 6 Dicembre - con aggiornamento entro le 24h precedenti. 

Puoi però tranquillamente intuirle/ricavarle & usarle per attività preliminari test/staging, riprendendo appunto l'attuale JSON delle Validation Rules & modificando semplicemente alcuni valori - in accordo alle disposizioni dell'[Art.3 DL n.172 26/11/2021](https://www.trovanorme.salute.gov.it/norme/dettaglioAtto?id=84133&articolo=3) = reimpostazione dei soli value per name `vaccine_end_day_complete` da 365 a 270.
 
> Le validation rules sono le stesse sia per la modalita' 2G e 3G? In pratica l'unica differenza 2G/3G sarebbe l'esclusione dei tamponi?

Corretto. 

Lo switch 3G->2G non incide sui value recuperati/aggiornati dal JSON Validation Rules, ma applica semplicemente un override sul flusso di validazione dei soli mapping T, restituendo in tal caso sempre esito NOT_VALID.

**Comment by bobbysimon24** [comment]
Ok, nuovamente grazie @rawmain 👍 
E anche a @lorenzob per aver sollevato la questione,
Buon lavoro a tutti
