### ISSUE TITLE
Informazioni pubblicazione app

### ISSUE THREAD

**Issue by bobbysimon24** [ministero-salute/it-dgc-verificac19-sdk-android#74]
Ciao a tutti, 
Mi chiedevo dove posso informarmi sulla pubblicazione di un'app di verifica, per capire quali punti deve seguire per essere ufficialmente utilizzabile per la verifica. Io non sto trovando niente a riguardo, ma credo ci sia un portale del genere no?

**Comment by loreberti89** [comment]
> Ciao a tutti, Mi chiedevo dove posso informarmi sulla pubblicazione di un'app di verifica, per capire quali punti deve seguire per essere ufficialmente utilizzabile per la verifica. Io non sto trovando niente a riguardo, ma credo ci sia un portale del genere no?

Ciao, ma non devi fare particolari cose per pubblicare una APP.
L'unica cosa che deve fare è, per la validazione, utilizzare solo ed esclusivamente le sdk ufficiali.
Se invece stai cercando una pagina per "pubblicare una sdk e farla diventare ufficiale" allora devi andare a guardare qua:
[https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding](https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding)

**Comment by rawmain** [comment]
Ciao @bobbysimon24 

> dove posso informarmi sulla pubblicazione di un'app di verifica, per capire quali punti deve seguire per essere ufficialmente utilizzabile per la verifica.

Come ti ha già indicato @loreberti89 , è sufficiente attenersi ai requisiti di conformità per sviluppo & utilizzo di verifier-app terze - indipendentemente dal fatto che siano disponibili/rilasciate su store pubblici, piuttosto che solo su canali privati/riservati per uso interno/aziendale.

Tali requisiti sono previsti/indicati nel [DPCM 12/10/2021](https://www.governo.it/sites/governo.it/files/DPCM_12_ottobre.pdf) : 

1. Utilizzo di SDK/Librerie validazione DGC con OK ufficiale del Ministero della Salute = SDK ufficiale Android/Kotlin + SDK terzi approvati & indicati in lista onboarding.

2. Ottemperanza a vincoli di trattamento dati QR per verifier-app ex art. 13 DPCM 12/10/2021 = minimizzazione dati esposti in esito validazione (_stile esiti VerificaC19_) e divieto di correlazioni/attività sui dati JSON QR per finalità distinte/slegate da verifica/validazione DGC

3. Allineamento puntuale con aggiornamenti / modifiche per gestione flussi di validazione (ved. DPCM/DL) in funzione di scenario/ambito di utilizzo

**Comment by bobbysimon24** [comment]
Grazie a tutti e due per la risposta,
Quello che volevo capire era esattamente questo, grazie @rawmain, perchè immaginavo ci fossero dei punti da rispettare per gli sviluppatori di app terze per poter fornire una verifica dei pass in maniera "certificata" dallo stato.
Come sempre molto utile, grazie
