### ISSUE TITLE
Duplicate in VerificationViewModel

### ISSUE THREAD

**Issue by NermeenSolaiman** [ministero-salute/it-dgc-verificac19-sdk-android#77]
**Describe the bug**
Il metodo **decode** in **VerificationViewModel** contiene un codice duplicato relativo al settaggio di **CertificateSimple**, di conseguenza il flag **scanMode** non ha alcun effetto.

**Current state**
```
            var certificateSimple = CertificateSimple()

            certificateSimple?.person?.familyName = certificateModel.person?.familyName
            certificateSimple?.person?.standardisedFamilyName =
                certificateModel.person?.standardisedFamilyName
            certificateSimple?.person?.givenName = certificateModel.person?.givenName
            certificateSimple?.person?.standardisedGivenName =
                certificateModel.person?.standardisedGivenName
            certificateSimple?.dateOfBirth = certificateModel.dateOfBirth

            if (certificateIdentifier == null || certificateIdentifier == "") {
                certificateSimple?.certificateStatus = CertificateStatus.NOT_VALID
            } else if (blackListCheckResult == true) {
                certificateSimple?.certificateStatus = CertificateStatus.NOT_VALID
            } else if (scanMode == "2G" && certificateModel.tests != null) {
                certificateSimple.certificateStatus = CertificateStatus.NOT_VALID
            } else if (fullModel == false) {
                if (getCertificateStatus(certificateModel) == CertificateStatus.NOT_VALID_YET) {
                    certificateSimple?.certificateStatus = CertificateStatus.NOT_VALID
                }
            }

//here a new setting of CertificateSimple that ocerrides the previous one
            val simpleCert = CertificateSimple()
            simpleCert.person?.familyName = certificateModel.person?.familyName
            simpleCert.person?.standardisedFamilyName =
                certificateModel.person?.standardisedFamilyName
            simpleCert.person?.givenName = certificateModel.person?.givenName
            simpleCert.person?.standardisedGivenName =
                certificateModel.person?.standardisedGivenName
            simpleCert.dateOfBirth = certificateModel.dateOfBirth

            if (isCertificateRevoked(certificateIdentifier.sha256())) {
                VerificaApplication.isCertificateRevoked = true
                simpleCert.certificateStatus = CertificateStatus.NOT_VALID
            } else {
                if (!fullModel) {
                    when {
                        getCertificateStatus(certificateModel) == CertificateStatus.NOT_VALID_YET -> {
                            simpleCert.certificateStatus = CertificateStatus.NOT_VALID
                        }
                        getCertificateStatus(certificateModel) == CertificateStatus.PARTIALLY_VALID -> {
                            simpleCert.certificateStatus = CertificateStatus.VALID
                        }
                        else -> {
                            simpleCert.certificateStatus =
                                getCertificateStatus(certificateModel)
                        }
                    }
                } else {
                    simpleCert.certificateStatus = getCertificateStatus(certificateModel)
                }
            }
```

**Expected behavior**
penso che dovrebbe essere qualcosa del tipo: 
```
            var certificateSimple = CertificateSimple()

            certificateSimple?.person?.familyName = certificateModel.person?.familyName
            certificateSimple?.person?.standardisedFamilyName =
                certificateModel.person?.standardisedFamilyName
            certificateSimple?.person?.givenName = certificateModel.person?.givenName
            certificateSimple?.person?.standardisedGivenName =
                certificateModel.person?.standardisedGivenName
            certificateSimple?.dateOfBirth = certificateModel.dateOfBirth

            if (certificateIdentifier == null || certificateIdentifier == "") {
                certificateSimple?.certificateStatus = CertificateStatus.NOT_VALID
            } else if (blackListCheckResult == true) {
                certificateSimple?.certificateStatus = CertificateStatus.NOT_VALID
            } else if (scanMode == "2G" && certificateModel.tests != null) {
                certificateSimple.certificateStatus = CertificateStatus.NOT_VALID
            } else if (fullModel == false) {
                if (getCertificateStatus(certificateModel) == CertificateStatus.NOT_VALID_YET) {
                    certificateSimple?.certificateStatus = CertificateStatus.NOT_VALID
                } else if (getCertificateStatus(certificateModel) == CertificateStatus.PARTIALLY_VALID) {
                    certificateSimple?.certificateStatus = CertificateStatus.VALID
                } else {
                    certificateSimple?.certificateStatus = getCertificateStatus(certificateModel)
                }
            } else { //show full model
                certificateSimple?.certificateStatus = getCertificateStatus(certificateModel)
            }
```
Ma non sono sicura di dove dovrebbe andare questa parte:
```
if (isCertificateRevoked(certificateIdentifier.sha256())) {
                VerificaApplication.isCertificateRevoked = true
                simpleCert.certificateStatus = CertificateStatus.NOT_VALID
            }
```
e 
```
else if (blackListCheckResult == true) {
                certificateSimple?.certificateStatus = CertificateStatus.NOT_VALID
            }
```

**Comment by dmanfroni** [comment]
Ci stavo sbattendo la testa pure io non capendo perché dava valido un Green Pass rilasciato con tampone se la App era impostata sul 2G.

Il problema è anche il metodo getCertificateStatus(certificateModel) in quanto restituirà sempre CertificateStatus.VALID perché non incrocia lo Scan Mode e il fatto che i test non sarebbero validi.

Se ti può aiutare ho risolto così

val certificateModel = greenCertificate.toCertificateModel(verificationResult)

            var certificateSimple = CertificateSimple()

            certificateSimple?.person?.familyName = certificateModel.person?.familyName
            certificateSimple?.person?.standardisedFamilyName =
                certificateModel.person?.standardisedFamilyName
            certificateSimple?.person?.givenName = certificateModel.person?.givenName
            certificateSimple?.person?.standardisedGivenName =
                certificateModel.person?.standardisedGivenName
            certificateSimple?.dateOfBirth = certificateModel.dateOfBirth
            certificateSimple?.certificateStatus = getCertificateStatus(certificateModel)

            if (certificateIdentifier == null || certificateIdentifier == "") {
                certificateSimple?.certificateStatus = CertificateStatus.NOT_VALID
            } else if (blackListCheckResult == true) {
                certificateSimple?.certificateStatus = CertificateStatus.NOT_VALID
            } else if (scanMode == "2G" && certificateModel.tests != null) {
                certificateSimple.certificateStatus = CertificateStatus.NOT_VALID
            } else if (isCertificateRevoked(certificateIdentifier.sha256())) {
                VerificaApplication.isCertificateRevoked = true
                certificateSimple.certificateStatus = CertificateStatus.NOT_VALID
            }else if (fullModel == false) {
                if (getCertificateStatus(certificateModel) == CertificateStatus.NOT_VALID_YET) {
                    certificateSimple?.certificateStatus = CertificateStatus.NOT_VALID
                }else if (getCertificateStatus(certificateModel) == CertificateStatus.PARTIALLY_VALID) {
                    certificateSimple?.certificateStatus = CertificateStatus.VALID
                }
            }

            certificateSimple.timeStamp = Date(System.currentTimeMillis())
            _certificate.value = certificateSimple

**Comment by bobbysimon24** [comment]
Ciao a tutti e due, se ho capito bene state facendo il mio stesso errore, guardate questo issue #65, lo avevo aperto per la stessa ragione più o meno. Dovete usare le release, non la versione develop, perchè contiene del codice che al momento possono utilizzare solo alcuni team autorizzati. Se volete provare comunque quella se guardate il mio issue @rawmain mi aveva fornito dei mock json da poter utilizzare finchè non avremo l'autorizzazione anche noi.

**Comment by rawmain** [comment]
Ciao @bobbysimon24 + @NermeenSolaiman + @dmanfroni 

> Dovete usare le release, non la versione develop, perchè contiene del codice che al momento possono utilizzare solo alcuni team autorizzati. Se volete provare comunque quella se guardate il mio issue @rawmain mi aveva fornito dei mock json da poter utilizzare finchè non avremo l'autorizzazione anche noi.

Corretto.

Per le implementazioni produzione di soluzioni integranti DGC-SDK Android/Kotlin allineato a prodrelease 1.1.8 PlayStore/AppGallery, va usato il codice in branch [release/1.0.4](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/release/1.0.4) - _senza apportarvi peraltro alcuna modifica come da vincoli DPCM 12/10/2021_.

Per effettuare invece attività preliminari di test/staging con il codice DGC-SDK WIP corrente (_quindi branch develop con/senza merge active branch feature/*_) è ancora necessario : 

1. Procedere temporaneamente di CRL Mock JSON

2. Revertare/fixare gli ultimi commit pre 24/11 legati a CRL (ved. [codice di confronto](https://github.com/VC19rvk/it-dgc-verificac19-sdk-android-RVK)) o integrare commit nuova PR #78 senza attendere merge.  

Per impostare il CRL Mock JSON, potete appunto riprendere l'impostazione di temp edit per API CRL endpoint in Apiservice.kt + arrangement JSON per mock - come da indicazioni in issue #65 .

---------------------------------

Un test-file esteso & aggiornato ad oggi (include gli hash SHA256 codificati Base64 delle 719 fraudulent/counterfeit entry attualmente in `black_list_uvci` Validation Rules + 1001 leaked entry) è disponibile [QUI](https://gist.github.com/rawmain/85ea0786ded9e4634ae13f467ef343ac). 

Potete usarlo come base per vs mock (_Postman, mockAPI, mocki, etc._) o anche richiamarlo direttamente, impostando i seguenti temp-commit al codice DGC-SDK WIP .

- Modifica in it-dgc-verificac19-sdk-android/sdk/build.gradle

```
         release {
            buildConfigField "String", "BASE_URL", "\"https://get.dgc.gov.it/v1/dgc/\""
            buildConfigField "String", "BASE_URL_CRL", "\"https://gist.githubusercontent.com/rawmain/85ea0786ded9e4634ae13f467ef343ac/raw/fdf2f6f9001b5ed5010492fea03fce497038874e/rvktest02.json\""
            buildConfigField "String", "BASE_URL_CRL_REVOKES", "\"https://gist.githubusercontent.com/rawmain/85ea0786ded9e4634ae13f467ef343ac/raw/fdf2f6f9001b5ed5010492fea03fce497038874e/rvktest02.json\""
            buildConfigField "String", "SERVER_HOST", "\"get.dgc.gov.it\""
            buildConfigField "String", "CERTIFICATE_SHA", "\"sha256/7cZJIDPacG8FS3pq6Mvxg+7yBDM/VYc2alOcbVe/e74=\""
            buildConfigField "String", "SDK_VERSION", "\"1.0.4\""

            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
```

- Modifica in it-dgc-verificac19-sdk-android/sdk/src/main/java/it/ministerodellasalute/verificaC19sdk/data/remote/ApiService.kt

```
    /** @GET("drl/check") */
    @GET(BuildConfig.BASE_URL_CRL)
    suspend fun getCRLStatus(@Query("version") version: Long?): Response<ResponseBody>

    /** @GET("drl") */
    @GET(BuildConfig.BASE_URL_CRL_REVOKES)
    suspend fun getRevokeList(@Query("version") version: Long?, @Query("chunk") chunk: Long?, ): Response<ResponseBody>
```

**Comment by Light2288** [comment]
@NermeenSolaiman thank you for reporting this bug, it will be closed by  https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/pull/78
