### ISSUE TITLE
Revocare la propria certificazione

### ISSUE THREAD

**Issue by BytesReturned** [ministero-salute/it-dgc-verificac19-sdk-android#79]
Buongiorno a tutti, stavo pensando che, siccome si parla spesso di liste di revoca, sarebbe bello avere la possibilità di revocare il proprio green pass di cui si ha subito il furto o lo si è perso in modo che non ci possano essere casi di frode con furto di green pass altrui.
Potrebbe essere implementata in questo modo:
accedo al sito dcg.gov.it e segnalo lo smarrimento/furto del green pass, il numero identificativo viene messo in una black list su un server e, la app di verifica segnala come non valido quel green pass mentre ne viene emesso uno nuovo della validità residua.
Mi rendo conto che ciò richiederebbe un intervento legislativo ma intanto propongo l'idea.
Fatemi sapere cosa ne pensate.

**Comment by giga89** [comment]
E se qualcuno inserisce il tuo green pass tra i revocati per farti un dispetto? :)

**Comment by mastro993** [comment]
Oltre al problema esposto da @giga89, basterebbe fare una foto di nascosto ad un green pass per poterlo utilizzare liberamente all'insaputa del proprietario. Inoltre non tutti tengono copia del formato digitale, una volta smarrito come fai a segnalare l'UVCI se non te lo ricordi? Potrebbero esserci poi casi di familiari che revocano il certificato a parenti (tipo figli) per privarli forzatamente di alcune libertà.
A mio parere, per quel che conta, è responsabilità di chi verifica il DGC controllare la corrispondenza del nome sul certificato con quello della persona che lo espone. Questo dovrebbe bastare a proteggere le persone dai furti.
Si sa però che la realtà è ben diversa... :)

**Comment by BytesReturned** [comment]
Infatti @mastro993 ha ragione, l'unico sistema per evitare abusi, è controllare il nome del green pass con quello di un documento ma pare che non si possa fare.
La funzione per revocare il green pass in caso di perdita sarebbe utile in certi casi ma si potrebbero verificare gli abusi gia descritti, se la questione è risolta 
chiudo l'issue ringraziando tutti.
