### ISSUE TITLE
Differenti formati di data in CertificateSimple.kt in field dateOfBirth

### ISSUE THREAD

**Issue by albertocappellina** [ministero-salute/it-dgc-verificac19-sdk-android#84]
# Issue content
Salve,

   come da oggetto durante la validazione di diversi greenpass ho ricevuto diversi formati nel campo dateOfBirth dell'oggetto CertificateSimple.

es: 
- yyyy-MM-dd
- yyyy-MM-dd'T'HH:mm:ss
- dd-MM-yyyy

E' corretto ?
Quali altri formati possono arrivare?

Grazie mille
Alberto

**Comment by rawmain** [comment]
Ciao @albertocappellina 

> come da oggetto durante la validazione di diversi greenpass ho ricevuto diversi formati nel campo dateOfBirth dell'oggetto CertificateSimple.
[...]
> E' corretto ? Quali altri formati possono arrivare?

Richiamando la funzione [formatDateOfBirth()](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/blob/develop/sdk/src/main/java/it/ministerodellasalute/verificaC19sdk/util/TimeUtility.kt) puoi comunque ottenere OK parsed string anche per DOB ridotti = non solo quindi formati contenenti giorno + mese + anno, ma anche solo mese + anno o soltanto l'anno di nascita.

**Comment by albertocappellina** [comment]
Grazie mille per la risposta @rawmain 

> Richiamando la funzione [formatDateOfBirth()](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/blob/develop/sdk/src/main/java/it/ministerodellasalute/verificaC19sdk/util/TimeUtility.kt) puoi comunque ottenere OK parsed string anche per DOB ridotti = non solo quindi formati contenenti giorno + mese + anno, ma anche solo mese + anno o soltanto l'anno di nascita.

tuttavia una data del tipo dd.MM.yyyy non viene gestita correttamente. Con la funzione formatDateOfBirth() 

23.04.1978

viene convertita in 0023.

**Comment by rawmain** [comment]
Ciao @albertocappellina 

> Grazie mille per la risposta @rawmain

Prego ;).

> tuttavia una data del tipo dd.MM.yyyy non viene gestita correttamente. Con la funzione formatDateOfBirth()

Il formato data DD-MM-YYYY (DDMMYYYY) NON è conforme a specifiche strict formati DOB **ISO 8601** per [schema EU DCC](https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_json_specification_en.pdf) (_Common structures and general requirements - Person name and date of birth_) - confermate anche per prossima versione schema [1.3.1](https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/release/1.3.1/DCC.schema.json) . 

Il parse di formatDateOfBirth() è conforme in modo strict allo schema & gestisce quindi correttamente solo questi formati data ISO 8601  : 

- YYYY-MM-DD (_YYYYMMDD_)
- YYYY-MM (_YYYYMM_)
- YYYY 

---------------------

Pertanto, qualora volessi comunque consentire alla tua verifier-app di gestire la visualizzazione UI data di nascita anche con eventuali DGC contenenti DOB fuori schema-strict ISO 8601 (_e.g. in formati DD-MM-YYYY e MM-YYYY_), potresti definire p.es. una tua funzione preliminare per controllo stringa data & eventuale rearrangement in formato ISO 8601 - prima di passarla a formatDateOfBirth().

Oppure, potresti anche semplicemente non usare formatDateOfBirth() definita in SDK, bensì in alternativa una funzione definita nel tuo codice app/UI, che provvedesse a tutte le operazioni : 

- check/rearrangement ISO 8601 [YYYY][MM][DD]
- check OK data compresa in intervallo 1900-01-01 <-> 2099-12-31
- parse/arrangement per stringa BirthDateText visualizzata da UI, eventualmente personalizzata (_e.g. indicando in UI il mese per nome, invece che per numero_)

**Comment by albertocappellina** [comment]
Grazie mille, ho inserito una routine per accettare i vari formati!
