### ISSUE TITLE
Verifica Green pass lenta

### ISSUE THREAD

**Issue by bobbysimon24** [ministero-salute/it-dgc-verificac19-sdk-android#89]
Facendo qualche test sulla mia app mi son accorto che ogni tanto la verifica di un green pass si blocca, va in loop o si "annulla", non capisco cosa esattamente perchè succede abbastanza a caso e non sono riuscito a debuggare ancora. Però quando si presenta non c'è verso di sbloccarlo, solo interrompendo l'esecuzione dell'app **a volte** si risolve il problema.
Succede spesso con i qr code presenti nella blacklist ma non solo con quelli, io sospetto sia un problema riguardante il database e il controllo dei certificati validi e quelli in blacklist ma sono solo mie ipotesi.
Qualcuno ha informazioni utili a riguardo? Succede solo a me?

**Comment by rawmain** [comment]
Ciao @bobbysimon24 

> Facendo qualche test sulla mia app mi son accorto che ogni tanto la verifica di un green pass si blocca, va in loop o si "annulla"
[...]
> Succede spesso con i qr code presenti nella blacklist ma non solo con quelli, io sospetto sia un problema riguardante il database e il controllo dei certificati validi e quelli in blacklist
[...]
> Succede solo a me?

Se fosse un problema generico del DGC-SDK Android/Kotlin, impattante l'uso tanto della whitelabel-app VerificaC19 quanto di app terze, vi sarebbe plausibilmente _qualche_ feedback pub in più su simili hang issue.

Il suggerimento è quindi quello di procedere con monitoraggio continuativo - tramite debug + logcat - della tua app, onde verificare in primis i processi preliminari di fetch/sync & reconciliation per i DB locali (KID, Blacklist, CRL) = i controlli di filtro avvengono offline, per cui eventuali anomalie lato DB semmai insorgono a monte (in fase di insert/reconciliation).

Nel caso non riuscissi eventualmente a venirne a capo per tuo conto, potresti ovviamente condividere qui log e/o riferimenti tuo codice app/UI & potremmo darci un'occhiata insieme.

**Comment by bobbysimon24** [comment]
Va bene, allora adesso provo, spero che serva perchè è abbastanza raro come problema quindi non so quando salterà fuori.
Ma secondo te @rawmain può essere dovuto anche a un dispositivo con prestazioni scadenti che per qualche motivo finisce in loop durante qualche decodifica del qr code? Perchè mi succede solo con dei tablet da tipo 200/300 euro, con il mio telefono (S21) non ho mai riscontrato il problema. Inoltre il problema era più frequente in particolare in un tablet difettoso che a volte si freezava da solo e che ora non si accende neanche più.

**Comment by rawmain** [comment]
Ciao @bobbysimon24 

> può essere dovuto anche a un dispositivo con prestazioni scadenti che per qualche motivo finisce in loop durante qualche decodifica del qr code? Perchè mi succede solo con dei tablet da tipo 200/300 euro, con il mio telefono (S21) non ho mai riscontrato il problema. Inoltre il problema era più frequente in particolare in un tablet difettoso che a volte si freezava da solo e che ora non si accende neanche più.

Come low-reference-device per test/benchmark di configurazioni analoghe a quelle dei totem ultimi 2 anni (_HW specs basse by design_) uso un GT-N5100 del 2013 con custom firmware Android 9/Pie & seguenti HW specs : 

- SOC QuadCore 1.6 GHz Cortex-A9
- 2GB RAM
- 16GB EMMC v4.5

OK performance in condizioni tanto prod quanto di test, e.g. insertion di 38 reference-chunk combinati CH+DE+FR+IT (per un totale di 378465 revoke) & successive query DB Realm per controllo filtri DGC.

Pertanto, a meno che tu stessi testando con dispositivi entry-level con RAM <= 1GB, tenderei cmq ad escludere questioni lato specs CPU/RAM/Storage.

Potrebbe dipendere invece p.es. da KO gestione camera nei dispositivi problematici (_dispositivi economici con SOC MTK non brillano per driver/ottimizzazione in merito_) per cui non verrebbe acquisita correttamente l'immagine, comportando quindi un'anomalia nei passaggi immagine->qrcodetext->validator.

E' una possibile ipotesi, ma ovviamente servono log per verificare se sia (o meno) la causa degli hang, che hai riscontrato.
