### ISSUE TITLE
Ambito di utilizzo nuova blacklist

### ISSUE THREAD

**Issue by DevTrevi** [ministero-salute/it-dgc-verificac19-sdk-android#92]
Buongiorno a tutti,
avrei bisogno di un chiarimento rispetto al contesto di utilizzo della nuova blacklist, in particolare mi servirebbe capire se va ad integrare la vecchia blacklist inclusa nei settings, oppure se deve sostituirla.

Ho fatto un test cercando gli identificativi della vecchia blacklist nella nuova, che ad oggi contiene 22808 record, e ho verificato che su 1996 identificativi presenti nella vecchia blacklist, 511 non sono presenti nella nuova.
Tra quelli mancanti ci sono ad esempio quello di Hitler, che sicuramente dovrebbe essere tra quelli esclusi.

E' possibile che la nuova blacklist contenga solo gli identificativi "sospesi" per malattia e che invece quelli fraudolenti siano inseriti solo in quella vecchia?

**Comment by rawmain** [comment]
Buongiorno @DevTrevi 

> mi servirebbe capire se va ad integrare la vecchia blacklist inclusa nei settings, oppure se deve sostituirla.

Per il momento vanno mantenuti integrati entrambi i controlli di filtro isRevoked & isBlacklisted, in allineamento con impostazioni correnti per DGC-SDK 1.1.0 & presenti ancora per prossima release DGC-SDK 1.1.1 .

Pertanto, va mantenuta la logic combinata di verifica/filtro UVCI : 

- **Blacklist** (_perm-block counterfeit/fraudulent & leaked_) : confronto diretto con UVCI recuperati da fetch/sync black_list_uvci in JSON Validation Rules

- **CRL/DRL** (_perm-block leaked + temp-block sospensioni per positività in TS_) : hash SHA-256 + codifica base64 & confronto con hash recuperati da fetch/consolidamento dei version-update chunk DRL

**Comment by DevTrevi** [comment]
Buongiorno @rawmain , ti ringrazio per la spiegazione, tutto chiaro 👍
