### ISSUE TITLE
Crash su validazione certificato quando device non ha connessione

### ISSUE THREAD

**Issue by salmattia** [ministero-salute/it-dgc-verificac19-sdk-android#97]
Quando l'app si avvia mentre il device è offline, la chiamata a `verificationViewModel.init(payload)` genera l'eccezione allegata.
Nel caso l'app sia offline `Realm.init(applicationContext)` non viene mai chiamato, da qui l'errore.
Ho verificato lo stesso comportamento sull'app VerificaC19 versione 1.2.0
E' un comportamento voluto? Significa che dobbiamo assicurarci che il device sia andato online almeno una volta durante la sessione di utilizzo per eseguire una validazione?
Grazie per l'aiuto
[realmcrash.txt](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/files/7788575/realmcrash.txt)

**Comment by rawmain** [comment]
Buongiorno @salmattia 

> Quando l'app si avvia mentre il device è offline, la chiamata a `verificationViewModel.init(payload)` genera l'eccezione allegata. Nel caso l'app sia offline `Realm.init(applicationContext)` non viene mai chiamato, da qui l'errore. Ho verificato lo stesso comportamento sull'app VerificaC19 versione 1.2.0 E' un comportamento voluto?

`Realm.init(applicationContext)` viene richiamato da `syncData`, che a sua volta viene richiamato dal fetch/sync del check CRL version/chunk di `getCRLStatus` in VerifierRepositoryImpl.kt .

Pertanto, se la chiamata a getCRLStatus viene effettuata in condizioni di esecuzione job con dispositivo offline, non si ottiene OK/successfull response alla relativa HTTPrequest. Corretto che non proceda oltre.

Se infatti prendi come riferimento la whitelabel-app VerificaC19 (_tanto release 1.2.0 con DGC-SDK 1.1.0 quanto 1.2.1 con DGC-SDK 1.1.1_), lanciandola in esecuzione dopo aver messo il dispositivo in modalità aereo, questa rimane in pending con l'indicazione "Aggiornamento in corso".

Mantenendo l'app in esecuzione & riabilitando la connettività del dispositivo, _quindi anche senza necessariamente chiuderla / riabilitare la connettività / riaprirla_, scaduto il timeout le response sono ok & avvengono fetch/sync.

Vedasi trace/sequenza eventi in logcat.

```
**dispositivo offline -> avvio app**

I LoadKeysWorker: key fetching start
V BaseRepository: Do network coroutine work
V BaseRepository: Do network coroutine work
[...]
I zygote64 -> sequenza di vari eventi correlati a KO request/response per fetch Rules in virtù di dispositivo offline

[...]

**app in esecuzione -> dispositivo di nuovo online**

V BaseRepository: Do network coroutine work
[...]
V BaseRepository: Do network coroutine work
[...]
I VerifierRepositoryImpl: Cert KID verified
V BaseRepository: Do network coroutine work
[...]
I CRL Status: it.ministerodellasalute.verificaC19sdk.data.remote.model.CrlStatus@5c993ec
I Reconciliation: final reconciliation completed!
I LoadKeysWorker: key fetching result: true
```

La whitelabel-app non crasha = puoi quindi usare il relativo codice come reference, per verificare la gestione delle exception nel vs. codice app/UI & correggere la situazione unhandled, che vi comporta tale Fatal Exception.

------------------

Per il resto, con fetch/sync Rules/KID/CRL completati correttamente, non ci sono questioni, che vietino anche di mettere offline il dispositivo & procedere con scansioni/validazioni. 

Infatti, se dopo sync OK l'app viene minimizzata in background, _rimanendo comunque in esecuzione / non-terminata da opzioni risparmio energetico dispositivo_, può essere richiamata per l'uso, mantenendo condizioni di offline - finché non scade il periodo base di esecuzione job dall'ultimo sync (_24h per whitelabel-app / personalizzabile per app terze, ma cmq non deve essere superiore alle 24h_).

Se invece l'esecuzione dell'app viene chiusa - _da operatore o dalle opzioni risparmio energetico dispositivo_ - allora il richiamo dell'app è comunque un nuovo avvio sessione, per cui viene avviato il worker & eseguito nuovo job per fetch/sync.

**Comment by salmattia** [comment]
Grazie @rawmain, mi è tutto chiaro.
Però quando eseguo un avvio dell'app mentre il device è offline, successivamente ad un fetch/sync riuscito con successo, mi trovo nella condizione in cui _qrButton_ è abilitato mentre il worker non è stato eseguito per effetto del constraint `.setRequiredNetworkType(NetworkType.CONNECTED)` settato sulla `WorkRequest`.
Di conseguenza in questa condizione l'app crasha quando eseguo la scansione di un qrcode.

Quindi riassumendo i passi per riprodurre il crash

1. Avvio l'app con device ONLINE e attendo il completamento del fetch/sync
2. Forzo la chiusura dell'app
3. Metto il device in modalità aereo
4. Riapro l'app
5. Clicco su "Scansiona il qr code"
6. Leggo un qrcode valido. Qui l'app va in crash con lo stack allegato sopra.

Grazie ancora per l'attenzione

**Comment by rawmain** [comment]
Ciao @salmattia 

> Grazie @rawmain, mi è tutto chiaro.

Prego ;).

> Però quando eseguo un avvio dell'app mentre il device è offline, successivamente ad un fetch/sync riuscito con successo, **mi  trovo nella condizione in cui _qrButton_ è abilitato** mentre il worker non è stato eseguito per effetto del constraint `.setRequiredNetworkType(NetworkType.CONNECTED)` settato sulla `WorkRequest`.
[...]
> 1. Avvio l'app con device ONLINE e attendo il completamento del fetch/sync
> 2. Forzo la chiusura dell'app
> 3. Metto il device in modalità aereo
> 4. Riapro l'app
> 5. **Clicco su "Scansiona il qr code"**
> 6. Leggo un qrcode valido. Qui l'app va in crash con lo stack allegato sopra.

Grazie intanto per gli ulteriori dettagli. 

Il punto critico riguarda però il passaggio evidenziato = gestione lato app/UI step 5 - avvio scansione.

Pertanto non riguarda DGC-SDK, bensì l'implementazione dei controlli lato codice app/UI.

Nel caso specifico della whitelabel-app VerificaC19, questa ne implementa alcuni - _vedansi observeSyncStatus() & trigger alert-dialog in FirstActivity.kt_ - ma non prevede comunque determinati controlli strict sul comportamento dell'operatore con il dispositivo.

Assunto base è infatti che cmq questi si attenga a indicazioni / linee guida per verifiche manuali = non proceda con le scansioni, se/finché il pannello in-app "**Ultimo aggiornamento dati e regole**" non confermi l'ok sync Rules/KIDs/CRL con l'indicazione di data/ora.

-----------------------

Niente vieta comunque di fare valutazioni/test per eventuale inoltro PR Enhancement in altra repo, cioè quella del codice whitelabel-app, che proponga l'aggiunta di ulteriori controlli.

Ho già fatto p.es. una verifica pratica con test-build per la casistica di comportamento operatore da te indicata -> può essere controllata, già semplicemente aggiungendo una condizione alternativa per il trigger di richiesta connessione ad Internet in FirstActivity.kt .

```
   [...]

   override fun onClick(v: View?) {

        if (v?.id == R.id.qrButton) {
            viewModel.getDateLastSync().let {
                if (!viewModel.getScanModeFlag() && v.id != R.id.scan_mode_button) {
                    createNoScanModeChosenAlert()
                    return
                } else if ((it == -1L) || (binding.dateLastSyncText.text == getString(R.string.loading))){
                    createNoSyncAlertDialog(getString(R.string.noKeyAlertMessage))
                    return
                }
            }
            [...]
```

-----------------------

Per quanto riguarda infine app terze, che integrano/usano DGC-SDK in conformità a commi 12-13 DPCM 12/10/2021, il discorso è analogo = impostazioni/livello dei controlli implementati dai relativi sviluppatori lato loro codice app/UI.

**Comment by salmattia** [comment]
Buonasera @rawmain, grazie per i chiarimenti. 
Nella nostra app avevamo già risolto il problema con una condizione analoga a quella da te indicata aggirando quindi il problema del crash. Senza dubbio il crash non si presenta più ma a mio parere, questa soluzione ha il limite di rendere necessaria la connettività all'avvio dell'app anche nel caso in cui l'ultimo sync/fetch completo sia stato eseguito con successo da meno di 24h.
Purtroppo questa condizione non è aggirabile da app terze integrando DGC-SDK alla versione attuale, quindi procederemo come da te consigliato con l'aggiunta di un controllo più stringente.

**Comment by salmattia** [comment]
Risolto con merge della pull #99. Chiudo la issue.
Grazie
